### ISSUE TITLE
[BUG] Furniture bug since 1.160.0

### ISSUE THREAD

**Issue by Xiao-MoMi** [oraxen/oraxen#1045]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

tomato_stage_4:
  material: SUGAR
  Mechanics:
    furniture:
      type: ITEM_FRAME
      limited_placing:
        roof: false
        floor: true
        wall: false
        type: DENY
        block_types: []
        block_tags: []
        oraxen_blocks: []
      barrier: false
  Pack:
    generate_model: false
    model: item/crops/tomato/stage_4
    custom_model_data: 1034

[02:38:14 ERROR]: Could not pass event EntityDamageByEntityEvent to Oraxen v1.160.0
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "this.minimalType" is null
        at io.th0rgal.oraxen.utils.drops.Drop.isTypeEnough(Drop.java:78) ~[oraxen-1.160.0.jar:?]
        at io.th0rgal.oraxen.utils.drops.Drop.canDrop(Drop.java:74) ~[oraxen-1.160.0.jar:?]
        at io.th0rgal.oraxen.utils.drops.Drop.furnitureSpawns(Drop.java:122) ~[oraxen-1.160.0.jar:?]
        at io.th0rgal.oraxen.api.OraxenFurniture.remove(OraxenFurniture.java:156) ~[oraxen-1.160.0.jar:?]
        at io.th0rgal.oraxen.mechanics.provided.gameplay.furniture.FurnitureListener.onPlayerBreakHanging(FurnitureListener.java:275) ~[oraxen-1.160.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor90.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[slimeworldmanager-api-1.20-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[slimeworldmanager-api-1.20-R0.1-SNAPSHOT.jar:git-SlimeWorldManager-15230]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[slimeworldmanager-api-1.20-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15230]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15230]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[slimeworldmanager-api-1.20-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:264) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15230]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1215) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15230]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1070) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15230]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callNonLivingEntityDamageEvent(CraftEventFactory.java:1268) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15230]
        at net.minecraft.world.entity.Interaction.skipAttackInteraction(Interaction.java:153) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15230]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1244) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2162) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2922) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2846) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15230]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1354) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15230]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15230]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1331) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15230]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1324) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15230]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1302) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15230]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1190) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15230]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[slimeworldmanager-1.20.1.jar:git-SlimeWorldManager-15230]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Steps to reproduce

break the furniture

### Plugin Version

1.160.0

### ProtocolLib Version

> version ProtocolLib
[04:20:48 INFO]: ProtocolLib version 5.1.0-SNAPSHOT-645
[04:20:48 INFO]: Provides read/write access to the Minecraft protocol.
[04:20:48 INFO]: Authors: dmulloy2 and comphenix

### Server Software & Version

[04:20:01 INFO]: Checking version, please wait...
[04:20:02 INFO]: This server is running SlimeWorldManager version git-SlimeWorldManager-15230 (MC: 1.20.1) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: 8ca908c on paper_upstream)
Unknown version
Previous version: git-Paper-102 (MC: 1.20.1)
>

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by bkgktp** [comment]
it is mandatory to enter the "drop" option in all created blocks because if you don't use it, the plugin gives such errors. this error did not exist before.

and also Oraxen doesn't support SlimeWorldManager because Oraxen furniture is saved in Bukkit PersistentDataContainer stacks, so I guess it might not work correctly if you use OraxenFurniture in SlimeWorldManager worlds.
