### ISSUE TITLE
[BUG] Error occurred while enabling Oraxen v1.162.1

### ISSUE THREAD

**Issue by GarryGale001110** [oraxen/oraxen#1078]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Oraxen lastest version can't be enabled in PaperSpigot1.18.1 
`[Oraxen] Plugin Oraxen v1.162.1 has failed to register events for class io.th0rgal.oraxen.font.FontEvents$PaperChatHandler because io/papermc/paper/event/player/AsyncChatDecorateEvent does not exist.
[20:00:04] [Server thread/ERROR]: Error occurred while enabling Oraxen v1.162.1 (Is it up to date?)
java.lang.NoSuchMethodError: 'net.kyori.adventure.text.format.TextDecorationAndState net.kyori.adventure.text.format.TextDecoration.withState(boolean)'
	at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.createNegated(DecorationTag.java:109) ~[?:?]
	at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.lambda$resolvers$2(DecorationTag.java:79) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310) ~[?:?]
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.lambda$static$3(DecorationTag.java:92) ~[?:?]
	at java.util.stream.Collectors.lambda$toMap$68(Collectors.java:1674) ~[?:?]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.<clinit>(DecorationTag.java:90) ~[?:?]
	at net.kyori.adventure.text.minimessage.tag.standard.StandardTags.<clinit>(StandardTags.java:48) ~[?:?]
	at net.kyori.adventure.text.minimessage.tag.resolver.TagResolver.standard(TagResolver.java:74) ~[?:?]
	at net.kyori.adventure.text.minimessage.MiniMessageImpl$Instances.lambda$static$0(MiniMessageImpl.java:57) ~[?:?]
	at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
	at net.kyori.adventure.text.minimessage.MiniMessageImpl$Instances.<clinit>(MiniMessageImpl.java:57) ~[?:?]
	at net.kyori.adventure.text.minimessage.MiniMessage.miniMessage(MiniMessage.java:54) ~[?:?]
	at io.th0rgal.oraxen.utils.AdventureUtils.<clinit>(AdventureUtils.java:24) ~[oraxen-1.162.1.jar:?]
	at io.th0rgal.oraxen.items.ItemParser.parseComponentDisplayName(ItemParser.java:74) ~[oraxen-1.162.1.jar:?]
	at io.th0rgal.oraxen.items.ItemParser.applyConfig(ItemParser.java:97) ~[oraxen-1.162.1.jar:?]
	at io.th0rgal.oraxen.items.ItemParser.buildItem(ItemParser.java:91) ~[oraxen-1.162.1.jar:?]
	at io.th0rgal.oraxen.config.ConfigsManager.parseItemConfig(ConfigsManager.java:297) ~[oraxen-1.162.1.jar:?]
	at io.th0rgal.oraxen.config.ConfigsManager.parseItemConfig(ConfigsManager.java:223) ~[oraxen-1.162.1.jar:?]
	at io.th0rgal.oraxen.api.OraxenItems.loadItems(OraxenItems.java:36) ~[oraxen-1.162.1.jar:?]
	at io.th0rgal.oraxen.OraxenPlugin.onEnable(OraxenPlugin.java:119) ~[oraxen-1.162.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:562) ~[paper-1.18.1.jar:git-Paper-216]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:476) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:736) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-216]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:00:04] [Server thread/INFO]: [Oraxen] Disabling Oraxen v1.162.1
[20:00:04] [Server thread/ERROR]: Error occurred while disabling Oraxen v1.162.1 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class io.th0rgal.oraxen.utils.AdventureUtils
	at io.th0rgal.oraxen.config.Message.send(Message.java:99) ~[oraxen-1.162.1.jar:?]
	at io.th0rgal.oraxen.config.Message.log(Message.java:115) ~[oraxen-1.162.1.jar:?]
	at io.th0rgal.oraxen.OraxenPlugin.onDisable(OraxenPlugin.java:156) ~[oraxen-1.162.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:562) ~[paper-1.18.1.jar:git-Paper-216]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:476) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:736) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.18.1.jar:git-Paper-216]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-216]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchMethodError: 'net.kyori.adventure.text.format.TextDecorationAndState net.kyori.adventure.text.format.TextDecoration.withState(boolean)' [in thread "Server thread"]
	at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.createNegated(DecorationTag.java:109) ~[?:?]
	at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.lambda$resolvers$2(DecorationTag.java:79) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310) ~[?:?]
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.lambda$static$3(DecorationTag.java:92) ~[?:?]
	at java.util.stream.Collectors.lambda$toMap$68(Collectors.java:1674) ~[?:?]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.kyori.adventure.text.minimessage.tag.standard.DecorationTag.<clinit>(DecorationTag.java:90) ~[?:?]
	at net.kyori.adventure.text.minimessage.tag.standard.StandardTags.<clinit>(StandardTags.java:48) ~[?:?]
	at net.kyori.adventure.text.minimessage.tag.resolver.TagResolver.standard(TagResolver.java:74) ~[?:?]
	at net.kyori.adventure.text.minimessage.MiniMessageImpl$Instances.lambda$static$0(MiniMessageImpl.java:57) ~[?:?]
	at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
	at net.kyori.adventure.text.minimessage.MiniMessageImpl$Instances.<clinit>(MiniMessageImpl.java:57) ~[?:?]
	at net.kyori.adventure.text.minimessage.MiniMessage.miniMessage(MiniMessage.java:54) ~[?:?]
	at io.th0rgal.oraxen.utils.AdventureUtils.<clinit>(AdventureUtils.java:24) ~[oraxen-1.162.1.jar:?]
	at io.th0rgal.oraxen.items.ItemParser.parseComponentDisplayName(ItemParser.java:74) ~[oraxen-1.162.1.jar:?]
	at io.th0rgal.oraxen.items.ItemParser.applyConfig(ItemParser.java:97) ~[oraxen-1.162.1.jar:?]
	at io.th0rgal.oraxen.items.ItemParser.buildItem(ItemParser.java:91) ~[oraxen-1.162.1.jar:?]
	at io.th0rgal.oraxen.config.ConfigsManager.parseItemConfig(ConfigsManager.java:297) ~[oraxen-1.162.1.jar:?]
	at io.th0rgal.oraxen.config.ConfigsManager.parseItemConfig(ConfigsManager.java:223) ~[oraxen-1.162.1.jar:?]
	at io.th0rgal.oraxen.api.OraxenItems.loadItems(OraxenItems.java:36) ~[oraxen-1.162.1.jar:?]
	at io.th0rgal.oraxen.OraxenPlugin.onEnable(OraxenPlugin.java:119) ~[oraxen-1.162.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	... 9 more`

### Steps to reproduce

1.Use PaperSpigot1.18.1
2.Start the server

### Plugin Version

1.162.1

### ProtocolLib Version

5.1

### Server Software & Version

1.18.1

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
should be fixed in latest releases. Gestures are better done through other means now, like MythicMobs, or dedicated plugins either way
