### ISSUE TITLE
[BUG] NoSuchElementException when using /oraxen gesture

### ISSUE THREAD

**Issue by Dymeth** [oraxen/oraxen#1104]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [x] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

```
Dymeth issued server command: /oraxen gesture jeqo.jeqo.gangnam_style
[CommandAPI] Unhandled exception executing '/oraxen gesture jeqo.jeqo.gangnam_style'
java.util.NoSuchElementException: null
        at com.google.common.collect.LinkedHashMultimap$ValueSet$1.next(LinkedHashMultimap.java:434) ~[guava-32.1.2-jre.jar:?]
        at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:473) ~[guava-32.1.2-jre.jar:?]
        at io.th0rgal.oraxen.shaded.playeranimator.nms.v1_20_R2.NMSHandler_v1_20_R2.getTexture(NMSHandler_v1_20_R2.java:85) ~[oraxen-1.164.0.jar:?]
        at io.th0rgal.oraxen.shaded.playeranimator.api.model.player.PlayerModel.<init>(PlayerModel.java:38) ~[oraxen-1.164.0.jar:?]
        at io.th0rgal.oraxen.gestures.OraxenPlayerModel.<init>(OraxenPlayerModel.java:15) ~[oraxen-1.164.0.jar:?]
        at io.th0rgal.oraxen.gestures.GestureManager.playGesture(GestureManager.java:28) ~[oraxen-1.164.0.jar:?]
        at io.th0rgal.oraxen.commands.GestureCommand.lambda$getGestureCommand$0(GestureCommand.java:40) ~[oraxen-1.164.0.jar:?]
        at dev.jorel.commandapi.executors.CommandExecutor.run(CommandExecutor.java:49) ~[?:?]
        at dev.jorel.commandapi.executors.NormalExecutor.executeWith(NormalExecutor.java:44) ~[?:?]
        at dev.jorel.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:140) ~[?:?]
        at dev.jorel.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:127) ~[?:?]
        at dev.jorel.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:96) ~[?:?]
        at dev.jorel.commandapi.CommandAPIHandler.lambda$generateCommand$0(CommandAPIHandler.java:258) ~[?:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[purpur-1.20.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:338) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2279) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2239) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1351) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1328) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1321) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1299) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2091]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Steps to reproduce

* Download bbmodel from https://drive.google.com/file/d/1Dg6pVMIiRUJHWt31eD7LZ-o4JTc3bz82/view?usp=sharing
* Stop server
* Add `jeqo.bbmodel` model to `gestures` folder
* Start server (there is no any errors in console)
* Run command: `/oraxen gesture jeqo.jeqo.gangnam_style`
* It will be error in console, no gesture will be displayed

### Plugin Version

Oraxen version 1.164.0

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT

### Server Software & Version

git-Purpur-2091 (MC: 1.20.2)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
library used for gestures seems to still have issues with 1.20.2
when that is fixed it should fix but seems this isnt an oraxen issue inherently
