### ISSUE TITLE
[BUG] Placing boat on Oraxen block crashes the server

### ISSUE THREAD

**Issue by Bruhhhh10** [oraxen/oraxen#1130]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

This only happens with NMS block correction on
When it crashes it drops a massive crash log in crash-reports folder and it looks something like this
	at net.minecraft.world.item.BoatItem.use(BoatItem.java:62)
	at oraxen-1.164.0.jar//io.th0rgal.oraxen.nms.v1_20_R2.NMSHandler.correctBlockStates(NMSHandler.java:110)
	at oraxen-1.164.0.jar//io.th0rgal.oraxen.utils.BlockHelpers.correctAllBlockStates(BlockHelpers.java:149)
	at oraxen-1.164.0.jar//io.th0rgal.oraxen.mechanics.provided.gameplay.noteblock.NoteBlockMechanicListener.makePlayerPlaceBlock(NoteBlockMechanicListener.java:528)
	at oraxen-1.164.0.jar//io.th0rgal.oraxen.mechanics.provided.gameplay.noteblock.NoteBlockMechanicListener.onPlaceAgainstNoteBlock(NoteBlockMechanicListener.java:284)
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor43.execute(Unknown Source)
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
	at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:595)
	at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:552)

### Steps to reproduce

Place oraxen block right click on it with a boat and it will crash the server

https://github.com/oraxen/oraxen/assets/134551265/9ec6de45-b7fc-4e77-8381-a665a0a93f45

### Plugin Version

1.164.0

### ProtocolLib Version

 5.1.1-SNAPSHOT-673

### Server Software & Version

git-Paper-298 (MC: 1.20.2)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
thanks, fixed next update, for now it is just disabled but it will eventually place properly
