### ISSUE TITLE
[BUG] Oraxen could not start

### ISSUE THREAD

**Issue by gamingcodedev** [oraxen/oraxen#1256]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

If i restart my server sometimes oraxen could not start

### Steps to reproduce

i rly don't know

Here is the issue:
[18:16:58] [Server thread/ERROR]: Error occurred while enabling Oraxen v1.169.0 (Is it up to date?)
java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method) ~[?:?]
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:101) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:60) ~[?:?]
	at sun.awt.PlatformGraphicsInfo.createGE(PlatformGraphicsInfo.java:36) ~[?:?]
	at java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:93) ~[?:?]
	at java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:84) ~[?:?]
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:106) ~[?:?]
	at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:224) ~[?:?]
	at sun.awt.PlatformGraphicsInfo.createToolkit(PlatformGraphicsInfo.java:40) ~[?:?]
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:599) ~[?:?]
	at java.awt.Image.getScaledInstance(Image.java:183) ~[?:?]
	at io.th0rgal.oraxen.utils.customarmor.CustomArmorsTextures.rescaleArmorImage(CustomArmorsTextures.java:351) ~[oraxen.jar:?]
	at io.th0rgal.oraxen.utils.customarmor.CustomArmorsTextures.registerImage(CustomArmorsTextures.java:100) ~[oraxen.jar:?]
	at io.th0rgal.oraxen.pack.generation.ResourcePack.readFileToVirtuals(ResourcePack.java:537) ~[oraxen.jar:?]
	at io.th0rgal.oraxen.pack.generation.ResourcePack.getAllFiles(ResourcePack.java:522) ~[oraxen.jar:?]
	at io.th0rgal.oraxen.pack.generation.ResourcePack.getAllFiles(ResourcePack.java:520) ~[oraxen.jar:?]
	at io.th0rgal.oraxen.pack.generation.ResourcePack.getAllFiles(ResourcePack.java:520) ~[oraxen.jar:?]
	at io.th0rgal.oraxen.pack.generation.ResourcePack.generate(ResourcePack.java:105) ~[oraxen.jar:?]
	at io.th0rgal.oraxen.OraxenPlugin.onEnable(OraxenPlugin.java:127) ~[oraxen.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-423]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-423]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-423]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-423]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-423]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-423]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-423]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-423]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-423]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Plugin Version

 v1.169.0

### Server Software & Version

1.20.4 PAPER

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
please use the discord for support
