### ISSUE TITLE
[BUG] Bow item fails to load

### ISSUE THREAD

**Issue by Mykindos** [oraxen/oraxen#1260]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When attempting to load certain items from a pack, in this case a bow, the plugin will error

`
java.lang.IllegalStateException: Not a JSON Object: null
        at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:101) ~[?:?]
        at io.th0rgal.oraxen.pack.generation.PredicatesGenerator.<init>(PredicatesGenerator.java:74) ~[oraxen-1.170.1.jar:?]
        at io.th0rgal.oraxen.pack.generation.ResourcePack.generatePredicates(ResourcePack.java:397) ~[oraxen-1.170.1.jar:?]
        at io.th0rgal.oraxen.pack.generation.ResourcePack.generate(ResourcePack.java:81) ~[oraxen-1.170.1.jar:?]
        at io.th0rgal.oraxen.api.OraxenPack.reloadPack(OraxenPack.java:47) ~[oraxen-1.170.1.jar:?]
        at io.th0rgal.oraxen.commands.ReloadCommand.reloadPack(ReloadCommand.java:60) ~[oraxen-1.170.1.jar:?]
        at io.th0rgal.oraxen.commands.ReloadCommand.lambda$getReloadCommand$1(ReloadCommand.java:102) ~[oraxen-1.170.1.jar:?]
        at dev.jorel.commandapi.executors.CommandExecutor.run(CommandExecutor.java:49) ~[?:?]
        at dev.jorel.commandapi.executors.NormalExecutor.executeWith(NormalExecutor.java:44) ~[?:?]
        at dev.jorel.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:137) ~[?:?]
        at dev.jorel.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:124) ~[?:?]
        at dev.jorel.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:91) ~[?:?]
        at dev.jorel.commandapi.CommandAPIHandler.lambda$generateCommand$0(CommandAPIHandler.java:258) ~[?:?]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[?:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[?:git-Paper-435]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[?:git-Paper-435]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[?:git-Paper-435]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[?:git-Paper-435]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[?:git-Paper-435]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
        at net.minecraft.commands.Commands.performPrefixedCommand(Commands.java:318) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:43) ~[?:git-Paper-435]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[?:git-Paper-435]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchServerCommand(CraftServer.java:984) ~[?:git-Paper-435]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:501) ~[?:git-Paper-435]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:448) ~[?:git-Paper-435]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1515) ~[?:git-Paper-435]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[?:git-Paper-435]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[?:git-Paper-435]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

This is my item config

`
custom_bow:
  Pack:
    generate_model: false
    model: custombow/bow
    pulling_models:
    - custombow/bow_0
    - custombow/bow_1
    - custombow/bow_2
    custom_model_data: 1000
  displayname: Custom Bow
  material: BOW
  permission: test.permission
`

If i change the material to PAPER, it loads correctly. However it goes without saying that I need it as a bow.

Not sure if I can submit the json's here as its a pack I purchased from mcmodels, but I know this error occurred with every pack I tried to load that contained a bow, it also happened for some other items like shields

### Steps to reproduce

1. Create a new yaml in Oraxen/items
2. Add configuration for a bow, i.e. 
`
custom_bow:
  Pack:
    generate_model: false
    model: custombow/bow
    pulling_models:
    - custombow/bow_0
    - custombow/bow_1
    - custombow/bow_2
    custom_model_data: 1000
  displayname: Custom Bow
  material: BOW
  permission: test.permission
`
3. Start server
4. Plugin will fail to load
5. Change material to PAPER
6. Restart server
7. Plugin will load properly

### Plugin Version

Oraxen | Oraxen version: 1.170.1!

### ProtocolLib Version

[07:12:21 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[07:12:21 INFO]: Provides read/write access to the Minecraft protocol.
[07:12:21 INFO]: Authors: dmulloy2 and comphenix

### Server Software & Version

[07:12:04 INFO]: This server is running Paper version git-Paper-435 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 681bbff)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-408 (MC: 1.20.4)
>

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
Seems you are missing the bow display setting in settings.yml
if you removed it, readd it and itll work @Mykindos
