### ISSUE TITLE
[BUG] Oraxen does not work when starting the server

### ISSUE THREAD

**Issue by NeroOrionn** [oraxen/oraxen#1282]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I can't use oraxen on my server, I bought it a few hours ago, I already looked and didn't find anything they say about it and I'm using ProtocolLib 5.1.0 and Oraxen 1.170.1 and I can't use it. (Sorry if something is written wrong, I'm using Google Translate)
erro:
[01:23:41] [Server thread/INFO]: [Oraxen] Enabling Oraxen v1.170.1
[01:23:43] [Server thread/INFO]: Oraxen | Version v1_19_R3 has been detected.
[01:23:43] [Server thread/INFO]: Oraxen | Oraxen will use the NMSHandler for this version.
[01:23:44] [Server thread/ERROR]: Error occurred while enabling Oraxen v1.170.1 (Is it up to date?)
        at io.th0rgal.oraxen.api.OraxenItems.loadItems(OraxenItems.java:37) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        
     and when I use ProtocolLib 5.0 these errors happen
        
        Error: 
  [01:29:12] [Server thread/INFO]: [Oraxen] Enabling Oraxen v1.170.1
[01:29:13] [Server thread/INFO]: Oraxen | Version v1_19_R3 has been detected.
[01:29:13] [Server thread/INFO]: Oraxen | Oraxen will use the NMSHandler for this version.
[01:29:14] [Server thread/ERROR]: Error occurred while enabling Oraxen v1.170.1 (Is it up to date?)
        at io.th0rgal.oraxen.items.ItemParser.parseOraxenSections(ItemParser.java:213) ~[?:?]
        at io.th0rgal.oraxen.items.ItemParser.applyConfig(ItemParser.java:125) ~[?:?]
        at io.th0rgal.oraxen.items.ItemParser.buildItem(ItemParser.java:110) ~[?:?]
        at io.th0rgal.oraxen.config.ConfigsManager.parseItemConfig(ConfigsManager.java:235) ~[?:?]
        at io.th0rgal.oraxen.api.OraxenItems.loadItems(OraxenItems.java:37) ~[?:?]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3763-Spigot-7d7b241-5a5e43e]

### Steps to reproduce

I place oraxen and ProtocolLib in the plugin folder and when I start the server I cannot use oraxen

### Plugin Version

1.170.1

### ProtocolLib Version

5.1.0

### Server Software & Version

Spigot 1.19.4 (java -version openjdk version "17.0.10" 2024-01-16)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
Hi, please stop by the support Discord, way easier to help there. Plugin should start without issues at all so this is indeed odd @NeroOrionn
