### ISSUE TITLE
[BUG] Error breaking custom block

### ISSUE THREAD

**Issue by ClumsyIsNotReal** [oraxen/oraxen#1384]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Error when mining a custom block and no drop from block
```
[21:44:25 ERROR]: Could not pass event BlockBreakEvent to Oraxen v1.174.0
java.lang.IllegalArgumentException: Enchantment cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.inventory.CraftMetaItem.hasEnchant(CraftMetaItem.java:945) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
        at io.th0rgal.oraxen.utils.drops.Drop.spawns(Drop.java:147) ~[oraxen-1.174.0.jar:?]
        at io.th0rgal.oraxen.api.OraxenBlocks.removeNoteBlock(OraxenBlocks.java:280) ~[oraxen-1.174.0.jar:?]
        at io.th0rgal.oraxen.api.OraxenBlocks.remove(OraxenBlocks.java:251) ~[oraxen-1.174.0.jar:?]
        at io.th0rgal.oraxen.api.OraxenBlocks.remove(OraxenBlocks.java:220) ~[oraxen-1.174.0.jar:?]
        at io.th0rgal.oraxen.mechanics.provided.gameplay.noteblock.NoteBlockMechanicListener.onBreakingCustomBlock(NoteBlockMechanicListener.java:269) ~[oraxen-1.174.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor412.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:git-Pufferfish-49]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.th0rgal.oraxen.utils.EventUtils.callEvent(EventUtils.java:20) ~[oraxen-1.174.0.jar:?]
        at io.th0rgal.oraxen.utils.breaker.BreakerSystem$1$1.accept(BreakerSystem.java:163) ~[oraxen-1.174.0.jar:?]
        at io.th0rgal.oraxen.utils.breaker.BreakerSystem$1$1.accept(BreakerSystem.java:141) ~[oraxen-1.174.0.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:103) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1653) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:450) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1532) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1227) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-49]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

### Steps to reproduce

Mine a custom block

### Plugin Version

Oraxen version 1.174.0
Authors: th0rgal and boy0000

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix

### Server Software & Version

This server is running Pufferfish version git-Pufferfish-49 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 852ea89 on HEAD)
You are on the latest version!

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
fixed next update 👍
