### ISSUE TITLE
[BUG] Could not pass event BlockBreakEvent to Oraxen v1.175.0 Minecraft V. 1.20.4

### ISSUE THREAD

**Issue by ParvatisGitHub** [oraxen/oraxen#1406]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When i break any noteblock block, including defaults of amythest and ruby ore, nothing drops. upon checking console i see this error message

[03:49:50] [Server thread/ERROR]: Could not pass event BlockBreakEvent to Oraxen v1.175.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:600) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:587) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.th0rgal.oraxen.utils.EventUtils.callEvent(EventUtils.java:20) ~[?:?]
	at io.th0rgal.oraxen.utils.breaker.BreakerSystem$1$1.accept(BreakerSystem.java:163) ~[?:?]
	at io.th0rgal.oraxen.utils.breaker.BreakerSystem$1$1.accept(BreakerSystem.java:141) ~[?:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:84) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4090-Spigot-b754dcc-38b1f49]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4090-Spigot-b754dcc-38b1f49]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1339) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4090-Spigot-b754dcc-38b1f49]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:391) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4090-Spigot-b754dcc-38b1f49]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1242) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4090-Spigot-b754dcc-38b1f49]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1054) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4090-Spigot-b754dcc-38b1f49]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4090-Spigot-b754dcc-38b1f49]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.IllegalArgumentException: org.bukkit.craftbukkit.v1_20_R3.block.impl.CraftNote data cannot be used for the STEP_SOUND effect
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:445) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.playEffect(CraftWorld.java:1189) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4090-Spigot-b754dcc-38b1f49]
	at org.bukkit.craftbukkit.v1_20_R3.CraftWorld.playEffect(CraftWorld.java:1182) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:4090-Spigot-b754dcc-38b1f49]
	at io.th0rgal.oraxen.api.OraxenBlocks.removeNoteBlock(OraxenBlocks.java:278) ~[?:?]
	at io.th0rgal.oraxen.api.OraxenBlocks.remove(OraxenBlocks.java:251) ~[?:?]
	at io.th0rgal.oraxen.api.OraxenBlocks.remove(OraxenBlocks.java:220) ~[?:?]
	at io.th0rgal.oraxen.mechanics.provided.gameplay.noteblock.NoteBlockMechanicListener.onBreakingCustomBlock(NoteBlockMechanicListener.java:269) ~[?:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 14 more

### Steps to reproduce

I placed an amythest ore block, went into survival mode and mined it with a diamond pickaxe and nothing drops. 

The only plugins on the server are Oraxen, ProtocolLib, and FastAsyncWorldEdit.
I ran the spigot build tools to make the 1.20.4 jar file for the server and I'm on a custom world.

I had a ton of other plugins on the server but i removed them all to try and diagnose the issue to no avail.
The only similar thing i could find was a bug report from 1.18.2

### Plugin Version

[04:06:00] [Server thread/INFO]: Oraxen version 1.175.0
[04:06:00] [Server thread/INFO]: Authors: th0rgal and boy0000

### ProtocolLib Version

[04:05:26] [Server thread/INFO]: ProtocolLib version 5.2.1-SNAPSHOT-689
[04:05:26] [Server thread/INFO]: Provides read/write access to the Minecraft protocol.
[04:05:26] [Server thread/INFO]: Authors: dmulloy2 and comphenix

### Server Software & Version

[04:06:45] [Server thread/INFO]: This server is running CraftBukkit version 4090-Spigot-b754dcc-38b1f49 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by ParvatisGitHub** [comment]
If anyone happens upon this looking for a solution- switching from spigot to paper fixed it. Hopefully it'll be resolved in the next few releases but for now paper fixes it
