### ISSUE TITLE
[BUG] ParsingExceptionImpl open inv

### ISSUE THREAD

**Issue by Euphillya** [oraxen/oraxen#1427]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

# Plugins : 
> pl
[18:24:40 INFO]: Server Plugins (2):
[18:24:40 INFO]: Bukkit Plugins:
[18:24:40 INFO]:  - Oraxen, ProtocolLib

In the latest version, 1.20.6, we have this bug:
```
[18:20:20 ERROR]: [CommandAPI] Unhandled exception executing '/o inv'
net.kyori.adventure.text.minimessage.internal.parser.ParsingExceptionImpl: Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.advntr.dev) for more information.
        §x§F§0§6§9§6§6C§x§F§3§8§4§7§6r§x§F§5§A§0§8§6o§x§F§8§B§B§9§6w§x§F§A§D§6§A§6n
          ^^
        at net.kyori.adventure.text.minimessage.internal.parser.TokenParser.parseString(TokenParser.java:170) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.internal.parser.TokenParser.resolvePreProcessTags(TokenParser.java:112) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageParser.parseToTree(MiniMessageParser.java:195) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageParser.parseFormat(MiniMessageParser.java:209) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:80) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:46) ~[adventure-text-minimessage-4.17.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.nms.v1_20_R4.ItemProperties.setItemName(ItemProperties.java:44) ~[oraxen-1.176.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.items.ItemBuilder.regen(ItemBuilder.java:531) ~[oraxen-1.176.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.items.ItemBuilder.build(ItemBuilder.java:683) ~[oraxen-1.176.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.utils.inventories.ItemsView.getGuiItemSlot(ItemsView.java:138) ~[oraxen-1.176.0.jar:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.max(ReferencePipeline.java:698) ~[?:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.utils.inventories.ItemsView.create(ItemsView.java:42) ~[oraxen-1.176.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.utils.inventories.InvManager.lambda$getItemsView$0(InvManager.java:26) ~[oraxen-1.176.0.jar:?]
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228) ~[?:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.utils.inventories.InvManager.getItemsView(InvManager.java:26) ~[oraxen-1.176.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.commands.CommandsManager.lambda$getInvCommand$2(CommandsManager.java:82) ~[oraxen-1.176.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.shaded.commandapi.executors.CommandExecutor.run(CommandExecutor.java:49) ~[oraxen-1.176.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.shaded.commandapi.executors.NormalExecutor.executeWith(NormalExecutor.java:44) ~[oraxen-1.176.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.shaded.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:137) ~[oraxen-1.176.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.shaded.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:124) ~[oraxen-1.176.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.shaded.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:91) ~[oraxen-1.176.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.shaded.commandapi.CommandAPIHandler.lambda$generateCommand$0(CommandAPIHandler.java:261) ~[oraxen-1.176.0.jar:?]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.commands.Commands.performCommand(Commands.java:355) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[18:20:20 ERROR]: Command exception: /o inv
net.kyori.adventure.text.minimessage.internal.parser.ParsingExceptionImpl: Legacy formatting codes have been detected in a MiniMessage string - this is unsupported behaviour. Please refer to the Adventure documentation (https://docs.advntr.dev) for more information.
        §x§F§0§6§9§6§6C§x§F§3§8§4§7§6r§x§F§5§A§0§8§6o§x§F§8§B§B§9§6w§x§F§A§D§6§A§6n
          ^^
        at net.kyori.adventure.text.minimessage.internal.parser.TokenParser.parseString(TokenParser.java:170) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.internal.parser.TokenParser.resolvePreProcessTags(TokenParser.java:112) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageParser.parseToTree(MiniMessageParser.java:195) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageParser.parseFormat(MiniMessageParser.java:209) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:80) ~[adventure-text-minimessage-4.17.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageImpl.deserialize(MiniMessageImpl.java:46) ~[adventure-text-minimessage-4.17.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.nms.v1_20_R4.ItemProperties.setItemName(ItemProperties.java:44) ~[oraxen-1.176.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.items.ItemBuilder.regen(ItemBuilder.java:531) ~[oraxen-1.176.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.items.ItemBuilder.build(ItemBuilder.java:683) ~[oraxen-1.176.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.utils.inventories.ItemsView.getGuiItemSlot(ItemsView.java:138) ~[oraxen-1.176.0.jar:?]
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
        at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.max(ReferencePipeline.java:698) ~[?:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.utils.inventories.ItemsView.create(ItemsView.java:42) ~[oraxen-1.176.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.utils.inventories.InvManager.lambda$getItemsView$0(InvManager.java:26) ~[oraxen-1.176.0.jar:?]
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228) ~[?:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.utils.inventories.InvManager.getItemsView(InvManager.java:26) ~[oraxen-1.176.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.commands.CommandsManager.lambda$getInvCommand$2(CommandsManager.java:82) ~[oraxen-1.176.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.shaded.commandapi.executors.CommandExecutor.run(CommandExecutor.java:49) ~[oraxen-1.176.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.shaded.commandapi.executors.NormalExecutor.executeWith(NormalExecutor.java:44) ~[oraxen-1.176.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.shaded.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:137) ~[oraxen-1.176.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.shaded.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:124) ~[oraxen-1.176.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.shaded.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:91) ~[oraxen-1.176.0.jar:?]
        at oraxen-1.176.0.jar/io.th0rgal.oraxen.shaded.commandapi.CommandAPIHandler.lambda$generateCommand$0(CommandAPIHandler.java:261) ~[oraxen-1.176.0.jar:?]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.commands.Commands.performCommand(Commands.java:355) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-145-fe7043e]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
>
```

### Steps to reproduce

New installation: Paper 1.20.6+ Oraxen + ProtocolLib
/o inv

### Plugin Version

18:22:28 INFO]: Oraxen version 1.176.0
[18:22:28 INFO]: Authors: th0rgal and boy0000

### ProtocolLib Version

[18:23:36 INFO]: ProtocolLib version 5.3.0-SNAPSHOT-720
[18:23:36 INFO]: Provides read/write access to the Minecraft protocol.
[18:23:36 INFO]: Authors: dmulloy2 and comphenix

### Server Software & Version

> version
[18:23:48 INFO]: Checking version, please wait...
[18:23:49 INFO]: This server is running Paper version 1.20.6-145-ver/1.20.6@fe7043e (2024-06-15T21:16:04Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version
>

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
Fixed next update already
