### ISSUE TITLE
[BUG] Incompatibility with Lands

### ISSUE THREAD

**Issue by thedarkonekiller** [oraxen/oraxen#1446]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

impossible to install Oraxen and Lands, i have tested if i remove oraxen the server starts, if i remove lands and readded oraxen the server starts.

[21:57:23 ERROR]: [SimpleProviderStorage] Circular plugin loading detected!
[21:57:23 ERROR]: [SimpleProviderStorage] Circular load order:
[21:57:23 ERROR]: [SimpleProviderStorage]   CMI -> eco -> Oraxen -> Lands -> CMI
[21:57:23 ERROR]: [SimpleProviderStorage] Please report this to the plugin authors of the first plugin of each loop or join the PaperMC Discord server for further help.
[21:57:23 ERROR]: [SimpleProviderStorage] If you would like to still load these plugins, acknowledging that there may be unexpected plugin loading issues, run the server with -Dpaper.useLegacyPluginLoading=true
[21:57:23 ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Circular plugin loading from plugins CMI
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.handleCycle(SimpleProviderStorage.java:78) ~[paper-1.21.jar:1.21-40-b45d9b6]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:42) ~[paper-1.21.jar:1.21-40-b45d9b6]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.jar:1.21-40-b45d9b6]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:535) ~[paper-1.21.jar:1.21-40-b45d9b6]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:290) ~[paper-1.21.jar:1.21-40-b45d9b6]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-40-b45d9b6]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-40-b45d9b6]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Steps to reproduce

Lands.jar + Oraxen.jar same time

### Plugin Version

Lands-7.6.4.jar
oraxen-1.177.0.jar

### ProtocolLib Version

ProtocolLib#723.jar

### Server Software & Version

papermc 1.21 last release

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by enesop** [comment]
This is an issue with CMI not lands or oraxen

**Comment by thedarkonekiller** [comment]
I also believed at the beginning but if I put only lands and oraxen without cmi I have the same error

**Comment by Boy0000** [comment]
As the error says you have a cycle dependency issue here

CMI hooks to eco which hooks to oraxen which hooks to lands which hooks back to cmi
breaking said chain by removing any of them would fix it
if u read the error it tells u how to also disable this paper startup feature

if you need them all there, not an oraxen bug

**Comment by thedarkonekiller** [comment]
ok I added the parameter to use legacy, it works but I find that it's not normal to do that, I also reported the problem to CMI but I don't really understand because if I make a server in 1.21 ( paper) and just Lands and Oraxen I have the same problem, so it would be more of a problem with paper? we'll see when we have a stable version of paper ;) thank you in any case for the help
