### ISSUE TITLE
[BUG] NoClassDefFoundError on BlockDamageEvent custom block

### ISSUE THREAD

**Issue by minustenchan** [oraxen/oraxen#1454]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

title

### Steps to reproduce

Mine a custom oraxen note block

stacktrace:

[07:11:29 ERROR]: Could not pass event BlockDamageEvent to oraxen v2.0-SNAPSHOT
java.lang.NoClassDefFoundError: Could not initialize class io.th0rgal.oraxen.utils.breaker.ToolTypeSpeedModifier
        at oraxen-2.0-SNAPSHOT.jar/io.th0rgal.oraxen.mechanics.provided.gameplay.BreakableMechanic.speedMultiplier(BreakableMechanic.java:55) ~[oraxen-2.0-SNAPSHOT.jar:?]
        at oraxen-2.0-SNAPSHOT.jar/io.th0rgal.oraxen.mechanics.provided.gameplay.BreakableMechanic.breakTime(BreakableMechanic.java:47) ~[oraxen-2.0-SNAPSHOT.jar:?]
        at oraxen-2.0-SNAPSHOT.jar/io.th0rgal.oraxen.utils.breaker.BreakerManager.startBlockBreak(BreakerManager.java:74) ~[oraxen-2.0-SNAPSHOT.jar:?]
        at oraxen-2.0-SNAPSHOT.jar/io.th0rgal.oraxen.mechanics.provided.gameplay.custom_block.CustomBlockMiningListener.onDamageCustomBlock(CustomBlockMiningListener.java:30) ~[oraxen-2.0-SNAPSHOT.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor121.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-45-4d20922]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-45-4d20922]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-45-4d20922]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callBlockDamageEvent(CraftEventFactory.java:662) ~[paper-1.21.jar:1.21-45-4d20922]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:266) ~[paper-1.21.jar:1.21-45-4d20922]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1785) ~[paper-1.21.jar:1.21-45-4d20922]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[paper-1.21.jar:1.21-45-4d20922]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[paper-1.21.jar:1.21-45-4d20922]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[paper-1.21.jar:1.21-45-4d20922]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-45-4d20922]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-45-4d20922]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-45-4d20922]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1541) ~[paper-1.21.jar:1.21-45-4d20922]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-45-4d20922]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-45-4d20922]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1518) ~[paper-1.21.jar:1.21-45-4d20922]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1511) ~[paper-1.21.jar:1.21-45-4d20922]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-45-4d20922]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1470) ~[paper-1.21.jar:1.21-45-4d20922]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1477) ~[paper-1.21.jar:1.21-45-4d20922]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1322) ~[paper-1.21.jar:1.21-45-4d20922]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-45-4d20922]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalArgumentException: WATER isn't an item [in thread "Server thread"]
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.inventory.ItemStack.of(ItemStack.java:58) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:138) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:117) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:104) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:87) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at oraxen-2.0-SNAPSHOT.jar/io.th0rgal.oraxen.nms.v1_21_R1.NMSHandler.lambda$itemTools$7(NMSHandler.java:294) ~[oraxen-2.0-SNAPSHOT.jar:?]
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at oraxen-2.0-SNAPSHOT.jar/io.th0rgal.oraxen.nms.v1_21_R1.NMSHandler.itemTools(NMSHandler.java:294) ~[oraxen-2.0-SNAPSHOT.jar:?]
        at oraxen-2.0-SNAPSHOT.jar/io.th0rgal.oraxen.utils.breaker.ToolTypeSpeedModifier.<clinit>(ToolTypeSpeedModifier.java:21) ~[oraxen-2.0-SNAPSHOT.jar:?]
        ... 31 more

### Plugin Version

2.0-SNAPSHOT

### ProtocolLib Version

5.3.0-SNPSHOT-723

### Server Software & Version

Paper version 1.21-45-master@4d20922

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
fixed
