### ISSUE TITLE
[BUG] Adventure issue with Purpur 1.20.4

### ISSUE THREAD

**Issue by sgdc3** [oraxen/oraxen#1460]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

After updating oraxen from version 1.776.0 to 1.178.0 the console is flooded with the following stacktrace error:
```java
[18:22:43] [Server thread/ERROR]: Could not pass event EntitiesLoadEvent to Oraxen v1.178.0
java.lang.NullPointerException: Cannot invoke "net.kyori.adventure.text.Component.style()" because "serializable" is null
	at net.kyori.adventure.text.minimessage.internal.serializer.SerializableResolver$Single.handle(SerializableResolver.java:130) ~[adventure-text-minimessage-4.16.0.jar:?]
	at net.kyori.adventure.text.minimessage.tag.resolver.SequentialTagResolver.handle(SequentialTagResolver.java:89) ~[adventure-text-minimessage-4.16.0.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageSerializer.visit(MiniMessageSerializer.java:70) ~[adventure-text-minimessage-4.16.0.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageSerializer.serialize(MiniMessageSerializer.java:57) ~[adventure-text-minimessage-4.16.0.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageImpl.serialize(MiniMessageImpl.java:99) ~[adventure-text-minimessage-4.16.0.jar:?]
	at net.kyori.adventure.text.minimessage.MiniMessageImpl.serialize(MiniMessageImpl.java:45) ~[adventure-text-minimessage-4.16.0.jar:?]
	at io.th0rgal.oraxen.items.ItemUpdater.lambda$updateItem$4(ItemUpdater.java:223) ~[oraxen-1.178.0.jar:?]
	at io.th0rgal.oraxen.utils.ItemUtils.editItemMeta(ItemUtils.java:45) ~[oraxen-1.178.0.jar:?]
	at io.th0rgal.oraxen.items.ItemUpdater.updateItem(ItemUpdater.java:137) ~[oraxen-1.178.0.jar:?]
	at io.th0rgal.oraxen.api.OraxenFurniture.updateFurniture(OraxenFurniture.java:280) ~[oraxen-1.178.0.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at io.th0rgal.oraxen.mechanics.provided.gameplay.furniture.FurnitureUpdater.lambda$new$0(FurnitureUpdater.java:30) ~[oraxen-1.178.0.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2176]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntitiesLoadEvent(CraftEventFactory.java:2035) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.world.ChunkEntitySlices.callEntitiesLoadEvent(ChunkEntitySlices.java:153) ~[purpur-1.20.4.jar:?]
	at net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:799) ~[?:?]
	at net.minecraft.world.level.chunk.LevelChunk.onChunkLoad(LevelChunk.java:750) ~[?:?]
	at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1339) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1383) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1367) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1320) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:418) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:903) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:414) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickMidTickTasks(MinecraftServer.java:1422) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.executeMidTickTasks(MinecraftServer.java:1445) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:650) ~[?:?]
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:491) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:889) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1759) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Steps to reproduce

Join the server

### Plugin Version

```
[21:22:10 INFO]: Oraxen version 1.178.0
[21:22:10 INFO]: Authors: th0rgal and boy0000
```

### ProtocolLib Version

```
[21:22:36 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[21:22:36 INFO]: Provides read/write access to the Minecraft protocol.
[21:22:36 INFO]: Authors: dmulloy2 and comphenix
```

### Server Software & Version

```
[21:23:15 INFO]: Current: git-Purpur-2176 (MC: 1.20.4)*
Previous: git-Purpur-2136 (MC: 1.20.4)
* You are running the latest version
```

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
please try using paper over purpur and see if that fixes it

**Comment by sgdc3** [comment]
@Boy0000 I'll try this as a debugging step, but please consider that Purpur is vital to my setup. Changing it would break many custom mechanics and degrade the server's performance.

**Comment by Boy0000** [comment]
In no scenario have i experienced purpur being more performant than paper, it just adds bloat and is slower to update because it is a fork
The onlyt difference between 1.176.0 and 1.178 thats relevant is oraxen updating to adventure 4.17 because 1.21
if this is an issue on purpurs end then it is an issue purpur needs to fix, cant say this happens on paper

oraxen "officially" supports paper and spigot (because it is on spigotmc)
most forks will work but i can in no way guarantee some forks dont do weird stuff that cause such issues

**Comment by sgdc3** [comment]
Just tried the latest Paper 1.20.4 build:

```java
[21:34:17 ERROR]: Could not pass event EntitiesLoadEvent to Oraxen v1.178.0                                                                                                                    |
java.lang.NullPointerException: Cannot invoke "net.kyori.adventure.text.Component.style()" because "serializable" is null
        at net.kyori.adventure.text.minimessage.internal.serializer.SerializableResolver$Single.handle(SerializableResolver.java:130) ~[adventure-text-minimessage-4.16.0.jar:?]
        at net.kyori.adventure.text.minimessage.tag.resolver.SequentialTagResolver.handle(SequentialTagResolver.java:89) ~[adventure-text-minimessage-4.16.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageSerializer.visit(MiniMessageSerializer.java:70) ~[adventure-text-minimessage-4.16.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageSerializer.serialize(MiniMessageSerializer.java:57) ~[adventure-text-minimessage-4.16.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageImpl.serialize(MiniMessageImpl.java:99) ~[adventure-text-minimessage-4.16.0.jar:?]
        at net.kyori.adventure.text.minimessage.MiniMessageImpl.serialize(MiniMessageImpl.java:45) ~[adventure-text-minimessage-4.16.0.jar:?]
        at io.th0rgal.oraxen.items.ItemUpdater.lambda$updateItem$4(ItemUpdater.java:223) ~[oraxen-1.178.0.jar:?]
        at io.th0rgal.oraxen.utils.ItemUtils.editItemMeta(ItemUtils.java:45) ~[oraxen-1.178.0.jar:?]
        at io.th0rgal.oraxen.items.ItemUpdater.updateItem(ItemUpdater.java:137) ~[oraxen-1.178.0.jar:?]
        at io.th0rgal.oraxen.api.OraxenFurniture.updateFurniture(OraxenFurniture.java:280) ~[oraxen-1.178.0.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at io.th0rgal.oraxen.mechanics.provided.gameplay.furniture.FurnitureUpdater.lambda$new$0(FurnitureUpdater.java:30) ~[oraxen-1.178.0.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-497]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntitiesLoadEvent(CraftEventFactory.java:2025) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.world.ChunkEntitySlices.callEntitiesLoadEvent(ChunkEntitySlices.java:153) ~[paper-1.20.4.jar:?]
        at net.minecraft.world.level.chunk.LevelChunk.loadCallback(LevelChunk.java:785) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunk.onChunkLoad(LevelChunk.java:736) ~[?:?]
        at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.handleFullStatusChange(NewChunkHolder.java:1339) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processPendingFullUpdate(ChunkHolderManager.java:1383) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1367) ~[paper-1.20.4.jar:git-Paper-497]
        at io.papermc.paper.chunk.system.scheduling.ChunkHolderManager.processTicketUpdates(ChunkHolderManager.java:1320) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.level.ServerChunkCache.runDistanceManagerUpdates(ServerChunkCache.java:415) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:860) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:411) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1453) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1343) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[paper-1.20.4.jar:git-Paper-497]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Boy0000** [comment]
sadly im not able to reproduce it and seems noone else has this issue either
no clue why it would be the case but try on a fresh server

for further support please use the discord

**Comment by sgdc3** [comment]
@Boy0000 ok found the issue in the code, you are not handling the case when meta.displayName() returns null, you should always check for meta.hasDisplayName first, as documented in the javadocs.

**Comment by Boy0000** [comment]
might be fixed there, issue isnt not checking hasdisplayname, issue is that displayname returns null whcih isnt supported in the Adventure deserializer method, feel free to compile the update and check if it works

**Comment by sgdc3** [comment]
> might be fixed there, issue isnt not checking hasdisplayname, issue is that displayname returns null whcih isnt supported in the Adventure deserializer method

That's what I was pointing at. My suggestion is to check the hasDisplayName method because it's what the Paper Javadoc says.
![image](https://github.com/user-attachments/assets/e064438a-640c-4e95-ba9c-7220d0416b21)

>feel free to compile the update and check if it works
Done! It seems to be working as expected.

**Comment by Boy0000** [comment]
yes iknow that it says such but if u look at the actual logic in the method, all it does is return null
null is safe and wanted in all places except that one spot

if its resolved feel free to close this 👍

**Comment by sgdc3** [comment]
@Boy0000 wait, does this mean you won't include this fix in the codebase?

**Comment by Boy0000** [comment]
?? i pushed the commit that fixes this issue and it is on the develop branch for next official update
so this issue can be closed

**Comment by sgdc3** [comment]
@Boy0000 oh sorry, didn't notice that 😄 
Thank you 👍🏻
