### ISSUE TITLE
[BUG] Plugin not starting

### ISSUE THREAD

**Issue by Vinnipapi** [oraxen/oraxen#1481]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

[15:40:06 INFO]: [PlayerAnimator] Enabling PlayerAnimator vR1.2.7
[15:40:06 ERROR]: Error occurred while enabling PlayerAnimator vR1.2.7 (Is it up to date?)
java.lang.IllegalStateException: Version not supported
at oraxen-1.179.0.jar/com.ticxo.playeranimator.PlayerAnimatorImpl.applyNMS(PlayerAnimatorImpl.java:78) ~[oraxen-1.179.0.jar:?]
at oraxen-1.179.0.jar/com.ticxo.playeranimator.PlayerAnimatorImpl.(PlayerAnimatorImpl.java:49) ~[oraxen-1.179.0.jar:?]
at oraxen-1.179.0.jar/com.ticxo.playeranimator.PlayerAnimatorImpl.initialize(PlayerAnimatorImpl.java:24) ~[oraxen-1.179.0.jar:?]
at oraxen-1.179.0.jar/com.ticxo.playeranimator.PlayerAnimatorPluginImpl.onEnable(PlayerAnimatorPluginImpl.java:11) ~[oraxen-1.179.0.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-123-0a1be9a]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-123-0a1be9a]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.jar:1.21-123-0a1be9a]
at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.jar:1.21-123-0a1be9a]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-123-0a1be9a]
at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[15:40:06 INFO]: [PlayerAnimator] Disabling PlayerAnimator vR1.2.7

On the Spigot Website says 1.21 ist tested in the latest build but it do not load...

### Steps to reproduce

Drag the latest Version in the plugins folder, start the server.

### Plugin Version

R1.2.7

### ProtocolLib Version

5.3.0-SNAPSHOT-726

### Server Software & Version

 1.21-123-master@0a1be9a

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
disable gestures

**Comment by Vinnipapi** [comment]
What do you mean with that?

**Comment by Boy0000** [comment]
exactly what i said, go into settings and disable gestures, use discord for further support 👍

**Comment by Vinnipapi** [comment]
I mean where I dont have access to plugin settings as it does not start up.

**Comment by Boy0000** [comment]
use the discord for further support if you cannot find the setting
you have access to the settings

**Comment by Vinnipapi** [comment]
I asked the discord now but as I said I cant access settings because the file is not generating because the plugin do not start up because of this error.

**Comment by Vinnipapi** [comment]
So how should I disable it? The folder only generates an empty folder called packs
