### ISSUE TITLE
[BUG] NoClassDefFoundError

### ISSUE THREAD

**Issue by exceptioncoding** [oraxen/oraxen#1502]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

[19:15:36] [Server thread/ERROR]: Error occurred while enabling Oraxen v1.180.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/wrappers/WrappedNumberFormat
	at io.th0rgal.oraxen.font.packets.ScoreboardPacketListener.<init>(ScoreboardPacketListener.java:16) ~[oraxen-1.180.0.jar:?]
	at io.th0rgal.oraxen.pack.generation.ResourcePack.hideScoreboardNumbers(ResourcePack.java:665) ~[oraxen-1.180.0.jar:?]
	at io.th0rgal.oraxen.pack.generation.ResourcePack.generate(ResourcePack.java:86) ~[oraxen-1.180.0.jar:?]
	at io.th0rgal.oraxen.OraxenPlugin.onEnable(OraxenPlugin.java:115) ~[oraxen-1.180.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.wrappers.WrappedNumberFormat
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:199) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:166) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	... 16 more

### Steps to reproduce

Download 1.20.4 Server and put Oraxen on it

### Plugin Version

Oraxen Version 1.180.0

### ProtocolLib Version

ProtocolLib v5.2.0

### Server Software & Version

Current: git-Purpur-2176 (MC: 1.20.4)*
* You are running the latest version

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
update protocollib

**Comment by exceptioncoding** [comment]
I'm using the latest Version that's available for 1.20.4!
