### ISSUE TITLE
[BUG] Random error or warnings in console (when user disconnects or connects)

### ISSUE THREAD

**Issue by NekrosBurek** [oraxen/oraxen#1530]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

My console starts spamming i am not 100% sure it is when users are disconnecting but based on the error i will provide this happens when user disconnects

```
> [12:10:46 INFO]: Dredlore lost connection: Disconnected
> [12:10:46 WARN]: java.lang.IllegalArgumentException: object is not an instance of declaring class
> [12:10:46 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(DirectMethodHandleAccessor.java:197)
> [12:10:46 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:99)
> [12:10:46 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
> [12:10:46 WARN]:        at oraxen-1.182.0.jar//io.th0rgal.oraxen.utils.InventoryUtils.topInventoryForPlayer(InventoryUtils.java:75)
> [12:10:46 WARN]:        at oraxen-1.182.0.jar//io.th0rgal.oraxen.mechanics.provided.misc.backpack.BackpackListener.closeBackpack(BackpackListener.java:131)
> [12:10:46 WARN]:        at oraxen-1.182.0.jar//io.th0rgal.oraxen.mechanics.provided.misc.backpack.BackpackListener.onPlayerDisconnect(BackpackListener.java:45)
> [12:10:46 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor282.execute(Unknown Source)
> [12:10:46 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
> [12:10:46 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
> [12:10:46 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
> [12:10:46 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
> [12:10:46 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
> [12:10:46 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
> [12:10:46 WARN]:        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:613)
> [12:10:46 WARN]:        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:598)
> [12:10:46 WARN]:        at net.minecraft.server.network.PlayerConnection.removePlayerFromWorld(PlayerConnection.java:2093)
> [12:10:46 WARN]:        at net.minecraft.server.network.PlayerConnection.onDisconnect(PlayerConnection.java:2073)
> [12:10:46 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2060)
> [12:10:46 WARN]:        at net.minecraft.network.NetworkManager.p(NetworkManager.java:838)
> [12:10:46 WARN]:        at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:254)
> [12:10:46 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1746)
> [12:10:46 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
> [12:10:46 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1525)
> [12:10:46 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226)
> [12:10:46 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
> [12:10:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

### Steps to reproduce

This happens randomly when server is active, potentially could be when user is disconnecting but don't want to mark as 100% the case

### Plugin Version

1.182.0

### ProtocolLib Version

5.2.1-SNAPSHOT-689

### Server Software & Version

Paper 1.20.4 (git-Paper-496)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by NekrosBurek** [comment]
Noticed now by doing a small research that this or at least one of the errors happen on item pickup

**Comment by Boy0000** [comment]
fixed next update
