### ISSUE TITLE
[BUG] Error building valid items

### ISSUE THREAD

**Issue by bakkbone** [oraxen/oraxen#1536]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

The following output occurs when attempting to reload Oraxen:
```
[20:05:39] [Server thread/INFO]: EmrysSMP | ERROR BUILDING ITEM "explorer_backpack_thirdperson"
[20:05:39] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because "<local2>" is null
[20:05:39] [Server thread/WARN]: 	at oraxen-1.182.0.jar//io.th0rgal.oraxen.items.ModelData.generateId(ModelData.java:40)
[20:05:39] [Server thread/WARN]: 	at oraxen-1.182.0.jar//io.th0rgal.oraxen.items.ItemParser.parseOraxenSections(ItemParser.java:365)
[20:05:39] [Server thread/WARN]: 	at oraxen-1.182.0.jar//io.th0rgal.oraxen.items.ItemParser.applyConfig(ItemParser.java:132)
[20:05:39] [Server thread/WARN]: 	at oraxen-1.182.0.jar//io.th0rgal.oraxen.items.ItemParser.buildItem(ItemParser.java:108)
[20:05:39] [Server thread/WARN]: 	at oraxen-1.182.0.jar//io.th0rgal.oraxen.config.ConfigsManager.parseItemConfig(ConfigsManager.java:320)
[20:05:39] [Server thread/WARN]: 	at oraxen-1.182.0.jar//io.th0rgal.oraxen.config.ConfigsManager.parseItemConfig(ConfigsManager.java:237)
[20:05:39] [Server thread/WARN]: 	at oraxen-1.182.0.jar//io.th0rgal.oraxen.api.OraxenItems.loadItems(OraxenItems.java:45)
[20:05:39] [Server thread/WARN]: 	at oraxen-1.182.0.jar//io.th0rgal.oraxen.commands.ReloadCommand.reloadItems(ReloadCommand.java:31)
[20:05:39] [Server thread/WARN]: 	at oraxen-1.182.0.jar//io.th0rgal.oraxen.commands.ReloadCommand.lambda$getReloadCommand$1(ReloadCommand.java:97)
[20:05:39] [Server thread/WARN]: 	at oraxen-1.182.0.jar//io.th0rgal.oraxen.shaded.commandapi.executors.CommandExecutor.run(CommandExecutor.java:49)
[20:05:39] [Server thread/WARN]: 	at oraxen-1.182.0.jar//io.th0rgal.oraxen.shaded.commandapi.executors.NormalExecutor.executeWith(NormalExecutor.java:44)
[20:05:39] [Server thread/WARN]: 	at oraxen-1.182.0.jar//io.th0rgal.oraxen.shaded.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:137)
[20:05:39] [Server thread/WARN]: 	at oraxen-1.182.0.jar//io.th0rgal.oraxen.shaded.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:124)
[20:05:39] [Server thread/WARN]: 	at oraxen-1.182.0.jar//io.th0rgal.oraxen.shaded.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:91)
[20:05:39] [Server thread/WARN]: 	at oraxen-1.182.0.jar//io.th0rgal.oraxen.shaded.commandapi.CommandAPIHandler.lambda$generateCommand$0(CommandAPIHandler.java:261)
[20:05:39] [Server thread/WARN]: 	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
[20:05:39] [Server thread/WARN]: 	at net.minecraft.commands.execution.tasks.ExecuteCommand.a(ExecuteCommand.java:31)
[20:05:39] [Server thread/WARN]: 	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19)
[20:05:39] [Server thread/WARN]: 	at net.minecraft.commands.execution.UnboundEntryAction.a(UnboundEntryAction.java:8)
[20:05:39] [Server thread/WARN]: 	at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5)
[20:05:39] [Server thread/WARN]: 	at net.minecraft.commands.execution.ExecutionContext.a(ExecutionContext.java:103)
[20:05:39] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:434)
[20:05:39] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:336)
[20:05:39] [Server thread/WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:323)
[20:05:39] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2230)
[20:05:39] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$14(PlayerConnection.java:2190)
[20:05:39] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[20:05:39] [Server thread/WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[20:05:39] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:05:39] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:149)
[20:05:39] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[20:05:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1465)
[20:05:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[20:05:39] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:123)
[20:05:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1442)
[20:05:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1365)
[20:05:39] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:133)
[20:05:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1343)
[20:05:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1232)
[20:05:39] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[20:05:39] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
```
Per: https://mclo.gs/1k2ZgjJ

### Steps to reproduce

Add this file as `\plugins\Oraxen\items\hmccosmetics.yml`:
```
arrow_next:
  displayname: Arrow (next)
  material: PAPER
  Pack:
    generate_model: false
    model: hmccosmetics/arrow_next
    custom_model_data: 1041

arrow_back:
  displayname: Arrow (back)
  material: PAPER
  Pack:
    generate_model: false
    model: hmccosmetics/arrow_back
    custom_model_data: 1042

colorful:
  displayname: HMCCosmetics Icon
  material: PAPER
  Pack:
    generate_model: false
    model: hmccosmetics/colorful
    custom_model_data: 1043

backpack:
  displayname: Backpack
  material: PAPER
  Pack:
    generate_model: false
    model: hmccosmetics/backpack
    custom_model_data: 1044

backpack_thirdperson:
  displayname: Backpack (thirdperson)
  material: PAPER
  Pack:
    generate_model: false
    model: hmccosmetics/backpack_thirdperson
    custom_model_data: 1045

paintbrush:
  displayname: Paintbrush
  material: POTION
  color: 255, 255, 255
  Pack:
    generate_model: false
    model: hmccosmetics/paintbrush

beanie:
  displayname: Beanie
  material: POTION
  color: 255, 255, 255
  Pack:
    generate_model: false
    model: hmccosmetics/beanie

lantern_cosmetic:
  displayname: Lantern Cosmetic
  material: PAPER
  Pack:
    generate_model: false
    model: hmccosmetics/lantern_cosmetic
    custom_model_data: 1046

baseball_hat:
  displayname: Baseball Hat
  material: PAPER
  Pack:
    generate_model: false
    model: hmccosmetics/baseball_hat
    custom_model_data: 1047

kite_item:
  displayname: Kite
  material: PAPER
  Pack:
    generate_model: false
    model: hmccosmetics/kite
    custom_model_data: 1048

future_wings:
  displayname: Future Wings
  material: PAPER
  Pack:
    generate_model: false
    model: hmccosmetics/future_wings
    custom_model_data: 1049

future_wings_thirdperson:
  displayname: Future Wings (thirdperson)
  material: PAPER
  Pack:
    generate_model: false
    model: hmccosmetics/future_wings_thirdperson
    custom_model_data: 1050

frog_hat:
  displayname: Frog Hat
  material: PAPER
  Pack:
    generate_model: false
    model: hmccosmetics/frog_hat
    custom_model_data: 1051

jetpack:
  displayname: Jetpack
  material: PAPER
  Pack:
    generate_model: false
    model: hmccosmetics/jetpack
    custom_model_data: 1052

hammer:
  displayname: Hammer
  material: PAPER
  Pack:
    generate_model: false
    model: hmccosmetics/hammer
    custom_model_data: 1053

explorer_backpack:
  displayname: Explorer's Backpack
  material: LEATHER_HORSE_ARMOR
  color: 255, 255, 255
  Pack:
    generate_model: false
    model: hmccosmetics/explorer_backpack

garbage_truck_balloon:
  displayname: Garbage Truck Balloon
  material: PAPER
  Pack:
    generate_model: false
    model: hmccosmetics/garbage_truck_balloon_item
    custom_model_data: 1054

earth_day_grabber:
  displayname: Earth Day Grabber
  material: LEATHER_HORSE_ARMOR
  color: 255, 255, 255
  Pack:
    generate_model: false
    model: hmccosmetics/earth_day_grabber

explorer_backpack_thirdperson:
  displayname: Explorer's Backpack
  material: LEATHER_HORSE_ARMOR
  color: 255, 255, 255
  Pack:
    generate_model: false
    model: hmccosmetics/explorer_backpack_thirdperson

jetpack_thirdperson:
  displayname: Jetpack
  material: PAPER
  Pack:
    generate_model: false
    model: hmccosmetics/jetpack_thirdperson
    custom_model_data: 1055

hibiscus_flower:
  displayname: Hibiscus Flower
  material: PAPER
  Pack:
    generate_model: false
    model: hmccosmetics/hibiscus_flower
    custom_model_data: 1056
```

### Plugin Version

Oraxen version 1.182.0

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### Server Software & Version

This server is running Paper version git-Paper-497 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: d8d54d9 on ver/1.20.4)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
should be fixed next update
