### ISSUE TITLE
[BUG] IllegalArgumentException: No enum constant org.bukkit.SoundCategory.RECORD

### ISSUE THREAD

**Issue by SrBedrock** [oraxen/oraxen#1589]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

```
[01:17:39 INFO]: [Oraxen] Enabling Oraxen v1.185.0
[01:17:39 INFO]: [Aviso] Version v1_20_R3 has been detected.
[01:17:39 INFO]: [Aviso] Oraxen will use the NMSHandler for this version.
[01:17:39 ERROR]: Error occurred while enabling Oraxen v1.185.0 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant org.bukkit.SoundCategory.RECORD
        at java.lang.Enum.valueOf(Enum.java:293) ~[?:?]
        at org.bukkit.SoundCategory.valueOf(SoundCategory.java:6) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.th0rgal.oraxen.sound.CustomSound.<init>(CustomSound.java:52) ~[Oraxen-1.185.0.jar:?]
        at io.th0rgal.oraxen.sound.SoundManager.<init>(SoundManager.java:28) ~[Oraxen-1.185.0.jar:?]
        at io.th0rgal.oraxen.OraxenPlugin.onEnable(OraxenPlugin.java:107) ~[Oraxen-1.185.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:653) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:564) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:346) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[01:17:39 INFO]: [Oraxen] Disabling Oraxen v1.185.0
```

### Steps to reproduce

Start server

### Plugin Version

```
[01:18:02 INFO]: Oraxen version 1.185.0
[01:18:02 INFO]: Authors: th0rgal and boy0000
```

### ProtocolLib Version

```
[01:18:13 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[01:18:13 INFO]: Provides read/write access to the Minecraft protocol.
[01:18:13 INFO]: Authors: dmulloy2 and comphenix
```

### Server Software & Version

```
[01:18:24 INFO]: Current: git-Purpur-2176 (MC: 1.20.4)*
* You are running the latest version
```

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by oliviathevampire** [comment]
I also have this issue

**Comment by patrick323** [comment]
same problem on paper 1.21.1

**Comment by Th0rgal** [comment]
Thanks will take a look

**Comment by Th0rgal** [comment]
Added to the backlog for next version

**Comment by CarmeloCampos** [comment]
+1 The same thing happens to me: 
I am using 1.185.0
![image](https://github.com/user-attachments/assets/d0d8a373-600e-4131-8ed3-67a0b6c6c824)
