### ISSUE TITLE
[BUG] 1.186.1 caused error when loading plugin in 1.20.1

### ISSUE THREAD

**Issue by killerprojecte** [oraxen/oraxen#1609]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0+
- [X] I have checked if any similar bug reports exist

### Description

[00:33:02] [Server thread/ERROR]: Error occurred while enabling Oraxen v1.186.1 (Is it up to date?)
java.lang.NoSuchMethodError: 'boolean com.google.gson.JsonObject.isEmpty()'
	at io.th0rgal.oraxen.pack.generation.PredicatesGenerator.<init>(PredicatesGenerator.java:148) ~[oraxen-1.186.1.jar:?]
	at io.th0rgal.oraxen.pack.generation.ResourcePack.generatePredicates(ResourcePack.java:449) ~[oraxen-1.186.1.jar:?]
	at io.th0rgal.oraxen.pack.generation.ResourcePack.generate(ResourcePack.java:98) ~[oraxen-1.186.1.jar:?]
	at io.th0rgal.oraxen.OraxenPlugin.onEnable(OraxenPlugin.java:116) ~[oraxen-1.186.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Steps to reproduce

Use Paper 1.20.1 to start server with oraxen

I resolve problem by shaded gson 2.11.0 and relocate it

### System Report

Plugin could not init

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Th0rgal** [comment]
thank will be fixed in 1.187.0
