### ISSUE TITLE
Texture pack problems

### ISSUE THREAD

**Issue by BookWyrm114** [oraxen/oraxen#199]
1: the new "need help?" banner shows up on the tooltips for emerald armor, I have regenerated the pack multiple times, and this still persists. screenshot:
![image](https://user-images.githubusercontent.com/79489385/128580196-c55aa0d5-f5db-46ed-a930-5de16b6517c2.png)

2: upon joining the server, and downloading the resourcepack, it kicks me and says that the pack could not be downloaded, and manually placing the zip file in my resource pack folder does not work, it shows up only if I unzip, and it works then, it also works if I export the unzipped file to dropbox, and then download it from there, I think it's a problem with the compression or something, also it might be that I use a mac, is there a way to fix this?

**Comment by Th0rgal** [comment]
Hey there!

Can you try to reset the Oraxen folder and then disable the pack protection in your config?


Thomas!

**Comment by BookWyrm114** [comment]
I had protection set to false before, but regenerating the entire oraxen folder seems to have fixed the issue, however the emerald armor still shows the "Need Help?" banner in the tooltip, and now the pack will not upload to the server correctly, upon startup it displays this message:

[10:45:52 INFO]: Oraxen | Automatic upload of the resource pack is enabled, uploading...
[10:45:52 INFO]: Oraxen | Successfully loaded on OS X null (10.15.5)

attempting to regenerate the pack says that the pack was not uploaded, most likely due to an excessive size, though the pack should now be a smaller size since I recently removed a lot of textures and sound files that were no longer needed

(current pack size: 15.9 MB)

the resource pack is not sent to players, and upon using a command to send the pack manually, this error appears:

[10:47:03 INFO]: java.lang.NullPointerException: Cannot invoke "io.th0rgal.oraxen.pack.dispatch.PackSender.sendPack(org.bukkit.entity.Player)" because the return value of "io.th0rgal.oraxen.pack.upload.UploadManager.getSender()" is null
[10:47:03 INFO]: 	at oraxen-1.99.3-all.jar//io.th0rgal.oraxen.commands.CommandsManager.lambda$getPackCommand$2(CommandsManager.java:44)
[10:47:03 INFO]: 	at oraxen-1.99.3-all.jar//io.th0rgal.oraxen.shaded.commandapi.executors.IExecutorNormal.executeWith(IExecutorNormal.java:43)
[10:47:03 INFO]: 	at oraxen-1.99.3-all.jar//io.th0rgal.oraxen.shaded.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:114)
[10:47:03 INFO]: 	at oraxen-1.99.3-all.jar//io.th0rgal.oraxen.shaded.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:102)
[10:47:03 INFO]: 	at oraxen-1.99.3-all.jar//io.th0rgal.oraxen.shaded.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:78)
[10:47:03 INFO]: 	at oraxen-1.99.3-all.jar//io.th0rgal.oraxen.shaded.commandapi.CommandAPIHandler.lambda$generateCommand$0(CommandAPIHandler.java:306)
[10:47:03 INFO]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
[10:47:03 INFO]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177)
[10:47:03 INFO]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:281)
[10:47:03 INFO]: 	at org.bukkit.craftbukkit.v1_17_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45)
[10:47:03 INFO]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[10:47:03 INFO]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:832)
[10:47:03 INFO]: 	at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2309)
[10:47:03 INFO]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2120)
[10:47:03 INFO]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2101)
[10:47:03 INFO]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[10:47:03 INFO]: 	at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[10:47:03 INFO]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[10:47:03 INFO]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[10:47:03 INFO]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[10:47:03 INFO]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[10:47:03 INFO]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1422)
[10:47:03 INFO]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[10:47:03 INFO]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[10:47:03 INFO]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1400)
[10:47:03 INFO]: 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1393)
[10:47:03 INFO]: 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[10:47:03 INFO]: 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1369)
[10:47:03 INFO]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1280)
[10:47:03 INFO]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[10:47:03 INFO]: 	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Th0rgal** [comment]
> I had protection set to false before, but regenerating the entire oraxen folder seems to have fixed the issue, however the emerald armor still shows the "Need Help?" banner in the tooltip, and now the pack will not upload to the server correctly, upon startup it displays this message:
> 
> [10:45:52 INFO]: Oraxen | Automatic upload of the resource pack is enabled, uploading...
> [10:45:52 INFO]: Oraxen | Successfully loaded on OS X null (10.15.5)
> 
> attempting to regenerate the pack says that the pack was not uploaded, most likely due to an excessive size, though the pack should now be a smaller size since I recently removed a lot of textures and sound files that were no longer needed
> 
> (current pack size: 15.9 MB)
> 
> the resource pack is not sent to players, and upon using a command to send the pack manually, this error appears:
> 
> [10:47:03 INFO]: java.lang.NullPointerException: Cannot invoke "io.th0rgal.oraxen.pack.dispatch.PackSender.sendPack(org.bukkit.entity.Player)" because the return value of "io.th0rgal.oraxen.pack.upload.UploadManager.getSender()" is null
> [10:47:03 INFO]: at oraxen-1.99.3-all.jar//io.th0rgal.oraxen.commands.CommandsManager.lambda$getPackCommand$2(CommandsManager.java:44)
> [10:47:03 INFO]: at oraxen-1.99.3-all.jar//io.th0rgal.oraxen.shaded.commandapi.executors.IExecutorNormal.executeWith(IExecutorNormal.java:43)
> [10:47:03 INFO]: at oraxen-1.99.3-all.jar//io.th0rgal.oraxen.shaded.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:114)
> [10:47:03 INFO]: at oraxen-1.99.3-all.jar//io.th0rgal.oraxen.shaded.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:102)
> [10:47:03 INFO]: at oraxen-1.99.3-all.jar//io.th0rgal.oraxen.shaded.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:78)
> [10:47:03 INFO]: at oraxen-1.99.3-all.jar//io.th0rgal.oraxen.shaded.commandapi.CommandAPIHandler.lambda$generateCommand$0(CommandAPIHandler.java:306)
> [10:47:03 INFO]: at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
> [10:47:03 INFO]: at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177)
> [10:47:03 INFO]: at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:281)
> [10:47:03 INFO]: at org.bukkit.craftbukkit.v1_17_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45)
> [10:47:03 INFO]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
> [10:47:03 INFO]: at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:832)
> [10:47:03 INFO]: at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2309)
> [10:47:03 INFO]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2120)
> [10:47:03 INFO]: at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2101)
> [10:47:03 INFO]: at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
> [10:47:03 INFO]: at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
> [10:47:03 INFO]: at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
> [10:47:03 INFO]: at net.minecraft.server.TickTask.run(TickTask.java:18)
> [10:47:03 INFO]: at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
> [10:47:03 INFO]: at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
> [10:47:03 INFO]: at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1422)
> [10:47:03 INFO]: at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
> [10:47:03 INFO]: at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
> [10:47:03 INFO]: at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1400)
> [10:47:03 INFO]: at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1393)
> [10:47:03 INFO]: at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
> [10:47:03 INFO]: at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1369)
> [10:47:03 INFO]: at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1280)
> [10:47:03 INFO]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
> [10:47:03 INFO]: at java.base/java.lang.Thread.run(Thread.java:831)

do you have an internet issue? For the glyphs, reset your font.yml file

**Comment by BookWyrm114** [comment]
reseting fonts.yml seems to have fixed the problem, but the texture pack is still not uploading correctly, my internet seems to be working fine, and I haven't had any issues recently, so I'm not sure what could be causing the problem

**Comment by BookWyrm114** [comment]
if it helps, I am running a paper fork called "Purpur", which might be causing it somehow

**Comment by Th0rgal** [comment]
It seems your pack file is too heavy.

**Comment by BookWyrm114** [comment]
ok, I do have a lot of custom stuff, i think I'll let oraxen compress the pack and upload the zip to dropbox to use it, thank you!
