### ISSUE TITLE
I might be doing smt wrong, but pls help...

### ISSUE THREAD

**Issue by flagz404** [oraxen/oraxen#211]
Hi, I just compiled the oraxen plugin and loaded it into my server and the server console throw me this:
```
[05:31:16 ERROR]: Error occurred while enabling Oraxen v1.116.0 (Is it up to date?)
java.lang.NoClassDefFoundError: dev/jorel/commandapi/CommandAPI
        at io.th0rgal.oraxen.OraxenPlugin.onEnable(OraxenPlugin.java:59) ~[oraxen-1.116.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:529) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:443) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:710) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:307) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1197) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: dev.jorel.commandapi.CommandAPI
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 11 more
[05:31:16 ERROR]: Error occurred while disabling Oraxen v1.116.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "io.th0rgal.oraxen.font.FontManager.unregisterEvents()" because "this.fontManager" is null
        at io.th0rgal.oraxen.OraxenPlugin.unregisterListeners(OraxenPlugin.java:98) ~[oraxen-1.116.0.jar:?]
        at io.th0rgal.oraxen.OraxenPlugin.onDisable(OraxenPlugin.java:92) ~[oraxen-1.116.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:529) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:443) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:710) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:307) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1197) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[patched_1.17.1.jar:git-Tuinity-"6fd7e2b"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```
I try adding in the `shaded` version and the `un-shaded` version into the server plugin folder and it still give me the error above, am I doing something wrong?

**Comment by Th0rgal** [comment]
Hello,

 You need to build it with gradle
