### ISSUE TITLE
BlockMechanicFactory#setBlockModel causing NPE

### ISSUE THREAD

**Issue by mfnalex** [oraxen/oraxen#216]
Oraxen version 1.116.0 on Paper 255 (1.17.1).

The following code:

```java
    public static void place(Block block, String name) {
        BlockMechanicFactory.setBlockModel(block, name); // <--- line 19 in OraxenHook.java
    }
```

causes this error:

```
[07:43:33 ERROR]: Could not pass event PlayerDeathEvent to AngelChest v4.11.0
java.lang.NullPointerException: Cannot invoke "io.th0rgal.oraxen.mechanics.MechanicFactory.getMechanic(String)" because "<local2>" is null
        at io.th0rgal.oraxen.mechanics.provided.gameplay.block.BlockMechanicFactory.setBlockModel(BlockMechanicFactory.java:84) ~[?:?]
        at de.jeff_media.angelchest.hooks.OraxenHook.place(OraxenHook.java:19) ~[?:?]
        at de.jeff_media.angelchest.data.MagicMaterial.placeInWorld(MagicMaterial.java:35) ~[?:?]
        at de.jeff_media.angelchest.data.AngelChest.createChest(AngelChest.java:355) ~[?:?]
        at de.jeff_media.angelchest.data.AngelChest.createChest(AngelChest.java:342) ~[?:?]
        at de.jeff_media.angelchest.data.AngelChest.createChest(AngelChest.java:338) ~[?:?]
        at de.jeff_media.angelchest.listeners.PlayerListener.spawnAngelChest(PlayerListener.java:810) ~[?:?]
        at de.jeff_media.angelchest.listeners.PlayerListener.spawnAngelChestHighest(PlayerListener.java:836) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor343.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-92]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-92]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-92]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-92]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:869) ~[patched_1.17.1.jar:git-Paper-92]
        at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:832) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1455) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:918) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:998) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.kill(LivingEntity.java:320) ~[?:?]
        at net.minecraft.server.commands.KillCommand.kill(KillCommand.java:32) ~[?:?]
        at net.minecraft.server.commands.KillCommand.lambda$register$2(KillCommand.java:25) ~[?:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[patched_1.17.1.jar:git-Paper-92]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[patched_1.17.1.jar:git-Paper-92]
        at net.minecraft.commands.Commands.a(Commands.java:275) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45) ~[patched_1.17.1.jar:git-Paper-92]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-92]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.1.jar:git-Paper-92]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2165) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1976) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1957) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-92]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-92]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-92]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-92]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-92]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1281) ~[patched_1.17.1.jar:git-Paper-92]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[patched_1.17.1.jar:git-Paper-92]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-92]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

The block I'm passing isn't null, and in a loaded chunk. The name of the block I passed was "cart", one of the default builtin blocks.

**Comment by Th0rgal** [comment]
Hello,

Is the blockmechanic loaded? Why aren't you using noteblock mechanic?

Thomas

**Comment by mfnalex** [comment]
That's the way as described in the API docs. I need users to be able to set something like "oraxen:cart" in my config.yml, and then my plugin uses oraxen's API to spawn the block. If there's a different alternative, I'd love to know how it works, but couldn't find anything in the docs at https://docs.oraxen.com/developers/api

**Comment by Boy0000** [comment]
Whenever #538 is merged this will be fixed. Keep in mind we have essentially deprecated the whole Block Mechanic as it is infinitely inferior to NoteBlockMechanic. So wont include specifically for it and eventually plan on entirely removing it.

But NoteBlock/Stringblock and funriture should get alot more API when done
