### ISSUE TITLE
Oraxen not loading

### ISSUE THREAD

**Issue by BookWyrm114** [oraxen/oraxen#222]
Hello, Upon starting up my server, or attempting to enable oraxen, oraxen will send this error and promptly disable itself:

[12:41:49 ERROR]: Error occurred while enabling Oraxen v1.116.2 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "io.th0rgal.oraxen.font.Glyph.getCharacter()" because "this.glyph" is null
	at io.th0rgal.oraxen.font.GlyphTransformation.apply(GlyphTransformation.java:46) ~[oraxen-1.116.2-all.jar:?]
	at io.th0rgal.oraxen.shaded.kyori.adventure.text.minimessage.MiniMessageParser.parse(MiniMessageParser.java:268) ~[oraxen-1.116.2-all.jar:?]
	at io.th0rgal.oraxen.shaded.kyori.adventure.text.minimessage.MiniMessageParser.parse(MiniMessageParser.java:274) ~[oraxen-1.116.2-all.jar:?]
	at io.th0rgal.oraxen.shaded.kyori.adventure.text.minimessage.MiniMessageParser.parseFormat0(MiniMessageParser.java:241) ~[oraxen-1.116.2-all.jar:?]
	at io.th0rgal.oraxen.shaded.kyori.adventure.text.minimessage.MiniMessageParser.parseFormat0(MiniMessageParser.java:172) ~[oraxen-1.116.2-all.jar:?]
	at io.th0rgal.oraxen.shaded.kyori.adventure.text.minimessage.MiniMessageParser.parseFormat(MiniMessageParser.java:156) ~[oraxen-1.116.2-all.jar:?]
	at io.th0rgal.oraxen.shaded.kyori.adventure.text.minimessage.MiniMessageImpl.parse(MiniMessageImpl.java:138) ~[oraxen-1.116.2-all.jar:?]
	at io.th0rgal.oraxen.pack.generation.ResourcePack.readFileToVirtuals(ResourcePack.java:264) ~[oraxen-1.116.2-all.jar:?]
	at io.th0rgal.oraxen.pack.generation.ResourcePack.getAllFiles(ResourcePack.java:244) ~[oraxen-1.116.2-all.jar:?]
	at io.th0rgal.oraxen.pack.generation.ResourcePack.generate(ResourcePack.java:98) ~[oraxen-1.116.2-all.jar:?]
	at io.th0rgal.oraxen.OraxenPlugin.onEnable(OraxenPlugin.java:73) ~[oraxen-1.116.2-all.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Purpur-1332]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1332]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1332]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:529) ~[patched_1.17.1.jar:git-Purpur-1332]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:443) ~[patched_1.17.1.jar:git-Purpur-1332]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:712) ~[patched_1.17.1.jar:git-Purpur-1332]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Purpur-1332]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1201) ~[patched_1.17.1.jar:git-Purpur-1332]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1332]
	at java.lang.Thread.run(Thread.java:831) [?:?]

I think this may be a problem with pupur, but I don't know for sure

**Comment by BookWyrm114** [comment]
This is a compatibility issue with purpur, I have tested oraxen on a purpur server (Build #1385) using Oraxen 1.116.3. no other plugins were present, and Oraxen failed to enable, sending this error message:

[18:43:26 ERROR]: Error occurred while enabling Oraxen v1.116.3 (Is it up to date?)
java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketAdapter
        at io.th0rgal.oraxen.mechanics.provided.gameplay.efficiency.EfficiencyMechanicFactory.<init>(EfficiencyMechanicFactory.java:13) ~[oraxen-1.116.3-all.jar:?]
        at io.th0rgal.oraxen.mechanics.MechanicsManager.registerMechanicFactory(MechanicsManager.java:100) ~[oraxen-1.116.3-all.jar:?]
        at io.th0rgal.oraxen.mechanics.MechanicsManager.registerNativeMechanics(MechanicsManager.java:64) ~[oraxen-1.116.3-all.jar:?]
        at io.th0rgal.oraxen.OraxenPlugin.onEnable(OraxenPlugin.java:66) ~[oraxen-1.116.3-all.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:727) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:318) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1216) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1385]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: com.comphenix.protocol.events.PacketAdapter
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:148) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[patched_1.17.1.jar:git-Purpur-1385]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 14 more
[18:43:26 ERROR]: Error occurred while disabling Oraxen v1.116.3 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "io.th0rgal.oraxen.font.FontManager.unregisterEvents()" because "this.fontManager" is null
        at io.th0rgal.oraxen.OraxenPlugin.unregisterListeners(OraxenPlugin.java:98) ~[oraxen-1.116.3-all.jar:?]
        at io.th0rgal.oraxen.OraxenPlugin.onDisable(OraxenPlugin.java:92) ~[oraxen-1.116.3-all.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:535) ~[patched_1.17.1.jar:git-Purpur-1385]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:449) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:727) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:318) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1216) ~[patched_1.17.1.jar:git-Purpur-1385]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Purpur-1385]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by BookWyrm114** [comment]
closing this to open a new issue on it with more detail on the error
