### ISSUE TITLE
Issue sending resource pack

### ISSUE THREAD

**Issue by Outlander87** [oraxen/oraxen#228]
Purpur 1.16.5 build 1171
ProtocolLib latest dev build
Oraxen 1.116.3

```16:29:18 WARN]: [ProtocolLib] Loaded class io.th0rgal.oraxen.pack.dispatch.AdvancedPackSender from Oraxen v1.116.3 which is not a depend, softdepend or loadbefore of this plugin.
[16:29:18 ERROR]: Could not pass event PlayerJoinEvent to Oraxen v1.116.3
com.comphenix.protocol.reflect.FieldAccessException: No field with type boolean exists in class PacketPlayOutResourcePackSend.
        at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:365) ~[?:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345) ~[?:?]
        at io.th0rgal.oraxen.pack.dispatch.AdvancedPackSender.sendPack(AdvancedPackSender.java:51) ~[?:?]
        at io.th0rgal.oraxen.pack.dispatch.AdvancedPackSender.onPlayerConnect(AdvancedPackSender.java:67) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor395.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-753]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-753]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-753]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-753]
        at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:356) ~[patched_1.16.5.jar:git-Paper-753]
        at net.minecraft.server.v1_16_R3.PlayerList.lambda$a$1(PlayerList.java:303) ~[patched_1.16.5.jar:git-Paper-753]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:316) ~[patched_1.16.5.jar:git-Paper-753]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:408) ~[patched_1.16.5.jar:git-Paper-753]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:168) ~[patched_1.16.5.jar:git-Paper-753]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1515) ~[patched_1.16.5.jar:git-Paper-753]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-753]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-753]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-753]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-753]
        at java.lang.Thread.run(Thread.java:831) [?:?]

```

**Comment by Th0rgal** [comment]
> Purpur 1.16.5 build 1171
> ProtocolLib latest dev build
> Oraxen 1.116.3
> 
> ```
> [16:29:18 ERROR]: Could not pass event PlayerJoinEvent to Oraxen v1.116.3
> com.comphenix.protocol.reflect.FieldAccessException: No field with type boolean exists in class PacketPlayOutResourcePackSend.
>         at com.comphenix.protocol.reflect.StructureModifier.writeInternal(StructureModifier.java:365) ~[?:?]
>         at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:345) ~[?:?]
>         at io.th0rgal.oraxen.pack.dispatch.AdvancedPackSender.sendPack(AdvancedPackSender.java:51) ~[?:?]
>         at io.th0rgal.oraxen.pack.dispatch.AdvancedPackSender.onPlayerConnect(AdvancedPackSender.java:67) ~[?:?]
>         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor395.execute(Unknown Source) ~[?:?]
>         at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-753]
>         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-753]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-753]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-753]
>         at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:356) ~[patched_1.16.5.jar:git-Paper-753]
>         at net.minecraft.server.v1_16_R3.PlayerList.lambda$a$1(PlayerList.java:303) ~[patched_1.16.5.jar:git-Paper-753]
>         at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:316) ~[patched_1.16.5.jar:git-Paper-753]
>         at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:408) ~[patched_1.16.5.jar:git-Paper-753]
>         at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:168) ~[patched_1.16.5.jar:git-Paper-753]
>         at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1515) ~[patched_1.16.5.jar:git-Paper-753]
>         at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-753]
>         at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-753]
>         at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-753]
>         at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-753]
>         at java.lang.Thread.run(Thread.java:831) [?:?]
> ```

hey,

please disable advanced pack sending in your settings
