### ISSUE TITLE
Dye command error

### ISSUE THREAD

**Issue by QuakyCZ** [oraxen/oraxen#239]
Hi,
dye command throws an error when the color string is not valid.

```log
[16:07:24 INFO]: Player issued server command: /o dye pink
[16:07:24 INFO]: java.lang.NumberFormatException: For input string: "in" under radix 16
[16:07:24 INFO]:        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
[16:07:24 INFO]:        at java.base/java.lang.Integer.parseInt(Integer.java:660)
[16:07:24 INFO]:        at java.base/java.lang.Integer.valueOf(Integer.java:965)
[16:07:24 INFO]:        at oraxen-1.117.0-all.jar//io.th0rgal.oraxen.commands.CommandsManager.hex2Rgb(CommandsManager.java:47)
[16:07:24 INFO]:        at oraxen-1.117.0-all.jar//io.th0rgal.oraxen.commands.CommandsManager.lambda$getDyeCommand$1(CommandsManager.java:60)
[16:07:24 INFO]:        at oraxen-1.117.0-all.jar//io.th0rgal.oraxen.shaded.commandapi.executors.IExecutorNormal.executeWith(IExecutorNormal.java:43)
[16:07:24 INFO]:        at oraxen-1.117.0-all.jar//io.th0rgal.oraxen.shaded.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:114)
[16:07:24 INFO]:        at oraxen-1.117.0-all.jar//io.th0rgal.oraxen.shaded.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:102)
[16:07:24 INFO]:        at oraxen-1.117.0-all.jar//io.th0rgal.oraxen.shaded.commandapi.CustomCommandExecutor.execute(CustomCommandExecutor.java:78)
[16:07:24 INFO]:        at oraxen-1.117.0-all.jar//io.th0rgal.oraxen.shaded.commandapi.CommandAPIHandler.lambda$generateCommand$0(CommandAPIHandler.java:307)
[16:07:24 INFO]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263)
[16:07:24 INFO]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177)
[16:07:24 INFO]:        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:282)
[16:07:24 INFO]:        at org.bukkit.craftbukkit.v1_17_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45)
[16:07:24 INFO]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[16:07:24 INFO]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:841)
[16:07:24 INFO]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2257)
[16:07:24 INFO]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2068)
[16:07:24 INFO]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2049)
[16:07:24 INFO]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[16:07:24 INFO]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[16:07:24 INFO]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[16:07:24 INFO]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[16:07:24 INFO]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[16:07:24 INFO]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[16:07:24 INFO]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418)
[16:07:24 INFO]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[16:07:24 INFO]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[16:07:24 INFO]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396)
[16:07:24 INFO]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389)
[16:07:24 INFO]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[16:07:24 INFO]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1367)
[16:07:24 INFO]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1278)
[16:07:24 INFO]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[16:07:24 INFO]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

**Comment by Rican14** [comment]
needs to be a hexcolor for example #123456

**Comment by Th0rgal** [comment]
> needs to be a hexcolor for example #123456

exactly! I'll soon add it to the /o command.

**Comment by QuakyCZ** [comment]
@Rican14 I know but it should be handled.
