### ISSUE TITLE
lower java version support

### ISSUE THREAD

**Issue by Sam-Chai** [oraxen/oraxen#267]
Im on 1.16.5, and I have some problem when my server use JDK 16 (some of plugins not support high java version), so i must use JDK 11 as a runtime.
but when i use java 11, the oraxen reports me a error:
```
[16:28:53][Server thread][ERROR]: Could not load 'plugins\oraxen-1.118.2-all.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `io.th0rgal.oraxen.OraxenPlugin'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:91) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:298) ~[forge:1.16.5-3850f2a]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:208) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:730) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:271) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.ClassNotFoundException: Failed to remap class io.th0rgal.oraxen.OraxenPlugin
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:258) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:160) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:121) ~[forge:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:89) ~[forge:?]
        ... 8 more
Caused by: java.lang.UnsupportedClassVersionError: io/th0rgal/oraxen/OraxenPlugin has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:250) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:160) ~[forge:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:121) ~[forge:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:89) ~[forge:?]
        ... 8 more
```

So, support lower java version please.

**Comment by Th0rgal** [comment]
Hello there,

If you want to use an old version of Spigot and Java you need to use an old version of Oraxen. Unfortunately Oraxen relies on dependencies that require recent versions of java and spigot (eg CommandAPI).

Thomas
