### ISSUE TITLE
[Bug Report] - NPE on Event

### ISSUE THREAD

**Issue by wdfeww** [oraxen/oraxen#268]
I am getting this exp by interacting with doors by using any custom oraxen block. 

`Could not pass event PlayerInteractEvent to Oraxen v1.121.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:504) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:484) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1533) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:33) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
        at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:151) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(SourceFile:23) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1157) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
        at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:125) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1136) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1129) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:134) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1113) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1037) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3332-Spigot-a5dea1c-bc14cb6]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.block.Block.getWorld()" because "<local8>" is null
        at io.th0rgal.oraxen.mechanics.provided.gameplay.noteblock.NoteBlockMechanicListener.onPrePlacingCustomBlock(NoteBlockMechanicListener.java:139) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        ... 22 more`

**Comment by Boy0000** [comment]
Closing this due to age of the issue, if it still applies on the latest versions of oraxen, i will reopen
