### ISSUE TITLE
java.lang.NoClassDefFoundError: me/lucko/commodore/CommodoreProvider

### ISSUE THREAD

**Issue by vibrantrida** [oraxen/Oraxen#28]
I get this error whenever the server enable Oraxen:
```
[19:04:54] [Server thread/INFO]: Reloading ResourceManager: Default, bukkit
[19:04:55] [Server thread/INFO]: Loaded 6 recipes
[19:04:55] [Server thread/ERROR]: Error occurred while enabling Oraxen v1.27.0 (Is it up to date?)
java.lang.NoClassDefFoundError: me/lucko/commodore/CommodoreProvider
	at io.th0rgal.oraxen.OraxenPlugin.registerCommands(OraxenPlugin.java:48) ~[?:?]
	at io.th0rgal.oraxen.OraxenPlugin.onEnable(OraxenPlugin.java:64) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-325]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-325]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-325]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-325]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-325]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-325]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-325]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900) ~[patched_1.15.2.jar:git-Paper-325]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.ClassNotFoundException: me.lucko.commodore.CommodoreProvider
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_231]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Paper-325]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-325]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_231]
	... 11 more
[19:04:55] [Server thread/INFO]: [Oraxen] Successfully unloaded
[19:04:55] [Server thread/INFO]: Running delayed init tasks
[19:04:55] [Server thread/INFO]: Done (21.611s)! For help, type "help"
```
[pastebin mirror](https://pastebin.com/TMWELVX3)

**Server Software:** Paper v1.15.2-325

**Comment by vibrantrida** [comment]
Fixed it by building a fat/shadow jar.

**Comment by Anath4n** [comment]
> Fixed it by building a fat/shadow jar.

fat shadow jar?
