### ISSUE TITLE
Task generate an exception when calling Vault API for offline players

### ISSUE THREAD

**Issue by StevenDouillet** [oraxen/oraxen#293]
Server version : 1.17.1 Pufferfish-20
Oraxen debug informations : 

![image](https://user-images.githubusercontent.com/41373474/155804006-1d2dac83-a9d0-479f-b14c-38131b28a9d6.png)

Stacktrace : 
```
[21:57:04] [Server thread/WARN]: [io.th0rgal.oraxen.OraxenPlugin] [Oraxen] <#e6a225>HistoryaPack <#636362>» <#f5f5f5> Task #4667628 for Oraxen v1.119.0 generated an exception
com.google.common.util.concurrent.UncheckedExecutionException: me.lucko.luckperms.bukkit.vault.ServerThreadLookupException: A Vault API request has been made on the main server thread that LuckPerms cannot safely respond to.
This is NOT a bug - please do not report it to LuckPerms.
Instead, please carefully read the information given below.

LuckPerms cannot respond to the request because to do so:
- it needs to lookup user data for 'b7fd0bea-743f-44ab-ad57-a324d0373a75' (an offline player) from the database

Performing this lookup on the main server thread would cause your server to lag.
There are two solutions to this problem:
  a) Ask the author of the plugin making the request to perform Vault calls for
     offline players "asynchronously" (using the scheduler). Additionally, prefer
     using the methods that accept 'Player' or 'OfflinePlayer' instead of usernames.
     You should be able to identify the plugin making the request in the trace below.
  b) As a server admin, you can disable this exception by setting 'vault-unsafe-lookups'
     to true in the LuckPerms configuration file. However, please use this only as
     a last resort.
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050) ~[patched_1.17.1.jar:git-Pufferfish-20]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951) ~[patched_1.17.1.jar:git-Pufferfish-20]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3973) ~[patched_1.17.1.jar:git-Pufferfish-20]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957) ~[patched_1.17.1.jar:git-Pufferfish-20]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4963) ~[patched_1.17.1.jar:git-Pufferfish-20]
	at com.sk89q.worldguard.session.AbstractSessionManager.hasBypass(AbstractSessionManager.java:161) ~[worldguard.jar:?]
	at com.sk89q.worldguard.bukkit.session.BukkitSessionManager.hasBypass(BukkitSessionManager.java:89) ~[worldguard.jar:?]
	at io.th0rgal.protectionlib.compatibilities.WorldGuardCompat.canBreak(WorldGuardCompat.java:52) ~[oraxen-1.119.0-all.jar:?]
	at io.th0rgal.protectionlib.ProtectionLib.lambda$canBreak$1(ProtectionLib.java:32) ~[oraxen-1.119.0-all.jar:?]
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
	at java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1728) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637) ~[?:?]
	at io.th0rgal.protectionlib.ProtectionLib.canBreak(ProtectionLib.java:32) ~[oraxen-1.119.0-all.jar:?]
	at io.th0rgal.oraxen.utils.breaker.BreakerSystem$1$1.accept(BreakerSystem.java:109) ~[oraxen-1.119.0-all.jar:?]
	at io.th0rgal.oraxen.utils.breaker.BreakerSystem$1$1.accept(BreakerSystem.java:92) ~[oraxen-1.119.0-all.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:103) ~[patched_1.17.1.jar:git-Pufferfish-20]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Pufferfish-20]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1569) ~[patched_1.17.1.jar:git-Pufferfish-20]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:495) ~[patched_1.17.1.jar:git-Pufferfish-20]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1485) ~[patched_1.17.1.jar:git-Pufferfish-20]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1284) ~[patched_1.17.1.jar:git-Pufferfish-20]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Pufferfish-20]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: me.lucko.luckperms.bukkit.vault.ServerThreadLookupException: A Vault API request has been made on the main server thread that LuckPerms cannot safely respond to.
This is NOT a bug - please do not report it to LuckPerms.
Instead, please carefully read the information given below.
```

**Comment by Boy0000** [comment]
Versions before 1.18 aren't supported anymore. If you can reproduce this issue on the latest versions of Oraxen i'll reopen this
