### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by DoctaEnkoda** [oraxen/Oraxen#37]
Bonjour, il y a un bug avec la "vol de vie", si la vie maximal est atteinte d'un joueur, une erreur se génère dans la console : 

``
Could not pass event EntityDamageByEntityEvent to Oraxen v1.34.0
java.lang.IllegalArgumentException: Health must be between 0 and 20.0, but was 20.999998092651367. (attribute base value: 20.0, player: Morex_78)
at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:112) ~[server.jar:git-Purpur-"da22eb0"]
at io.th0rgal.oraxen.mechanics.provided.lifeleech.LifeLeechMechanicListener.onCall(LifeLeechMechanicListener.java:35) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor72.execute(Unknown Source) ~[?:?]
``

Rajouter une condition pour vérifier la vie maximum actuelle du joueur ou entité.

**Comment by Th0rgal** [comment]
En effet, merci pour le report ! Je vais corriger ça au plus vite.

**Comment by Th0rgal** [comment]
Fixed in last commit: https://github.com/oraxen/Oraxen/commit/397bca4bcd446e407bf1df1728f88fa80ec2423e
