### ISSUE TITLE
Error occurred when starting the server (paper1.19)

### ISSUE THREAD

**Issue by SammyInMinecraft** [oraxen/oraxen#441]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

An error occurs when I open the server .
The latest version just downloaded .

### Steps to reproduce

Install the latest version of oraxen and build the latest protocollib 
Start the server
download libraries
Happened
`[15:50:28 ERROR]: Error occurred while enabling Oraxen v1.139.1 (Is it up to date?)
java.lang.NoSuchMethodError: 'boolean org.bukkit.Bukkit.shouldSendChatPreviews()'
        at io.th0rgal.oraxen.shaded.commandapi.nms.NMS_1_19_Common.canUseChatPreview(NMS_1_19_Common.java:267) ~[oraxen-1.139.1.jar:?]
        at io.th0rgal.oraxen.shaded.commandapi.CommandAPI.onEnable(CommandAPI.java:214) ~[oraxen-1.139.1.jar:?]
        at io.th0rgal.oraxen.OraxenPlugin.onEnable(OraxenPlugin.java:61) ~[oraxen-1.139.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:554) ~[paper-1.19.jar:git-Paper-27]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:468) ~[paper-1.19.jar:git-Paper-27]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-27]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-27]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-27]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-27]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-27]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:50:28 ERROR]: Error occurred while disabling Oraxen v1.139.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "io.th0rgal.oraxen.font.FontManager.unregisterEvents()" because "this.fontManager" is null
        at io.th0rgal.oraxen.OraxenPlugin.unregisterListeners(OraxenPlugin.java:101) ~[oraxen-1.139.1.jar:?]
        at io.th0rgal.oraxen.OraxenPlugin.onDisable(OraxenPlugin.java:95) ~[oraxen-1.139.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:573) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:536) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:554) ~[paper-1.19.jar:git-Paper-27]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:468) ~[paper-1.19.jar:git-Paper-27]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:633) ~[paper-1.19.jar:git-Paper-27]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:419) ~[paper-1.19.jar:git-Paper-27]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.jar:git-Paper-27]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1121) ~[paper-1.19.jar:git-Paper-27]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-27]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

### Plugin Version

Oraxen version : 1.139.1

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT

### Server Version

Paperspigot version  git-Paper-40 (MC: 1.19)
Java version 18.0.1 

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
did you download it from Polymart or Spigot @SammyInMinecraft

**Comment by SammyInMinecraft** [comment]
> 

No, I built it on GitHub. I haven't planned to buy it yet because I haven't tried to use oraxen

**Comment by Boy0000** [comment]
Cant really provide support for people building the jar.
Neither can i replicatre this issue on Paper myself on 1.18->1.19.2

**Comment by SammyInMinecraft** [comment]
All right, thx

**Comment by Boy0000** [comment]
Just set up a brand new test server locally and tried Oraxen on 1.18.1->1.19.2 with latest release
Having no issues what so ever. Please try and start your server with **only** Oraxen and ProtocolLib 5.0.0 on.
If it still fails its probably due to some server setting, if not probably another plugin. By the looks of it its CommandAPI failing, but no reason it should

**Comment by SammyInMinecraft** [comment]
I rebuilt and solved this problem on another computer
I don't know exactly what this is, but it can be used normally

**Comment by Boy0000** [comment]
Your protocollib is outdated @PainOchoco

**Comment by PainOchoco** [comment]
I dont think so, I'm using ProtocolLib v.5.0.0

**Comment by Boy0000** [comment]
This error is caused by an outdated 5.0 dev version. Use the support for future, as this is closed and resolved 👍
