### ISSUE TITLE
[BUG] ExceptionInInitializerError

### ISSUE THREAD

**Issue by DoctaEnkoda** [oraxen/oraxen#498]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

Error : 
```
[13:43:13 Craft Scheduler Thread - 4 - Oraxen/WARN][OraxenPlugin] - [Oraxen] <gradient:#9055FF:#13E2DA>Oraxen <#282B3F>|  Plugin Oraxen v1.143.1 generated an exception while executing task 61
java.lang.ExceptionInInitializerError: null
        at io.th0rgal.oraxen.pack.dispatch.AdvancedPackSender.<init>(AdvancedPackSender.java:29) ~[oraxen-1.143.1.jar:?]
        at io.th0rgal.oraxen.pack.upload.UploadManager.lambda$uploadAsyncAndSendToPlayers$0(UploadManager.java:75) ~[oraxen-1.143.1.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-35]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[multipaper-1.19.2.jar:MultiPaper-1.19.2-35]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[multipaper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: Cannot find ChatComponentText class.
        at com.comphenix.protocol.utility.MinecraftReflection.getChatComponentTextClass(MinecraftReflection.java:831) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.WrappedChatComponent.<clinit>(WrappedChatComponent.java:56) ~[ProtocolLib.jar:?]
        ... 8 more
Caused by: java.lang.RuntimeException: Unable to find network.chat.ChatComponentText (ChatComponentText)
        at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:2159) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.utility.MinecraftReflection.getChatComponentTextClass(MinecraftReflection.java:816) ~[ProtocolLib.jar:?]
        at com.comphenix.protocol.wrappers.WrappedChatComponent.<clinit>(WrappedChatComponent.java:56) ~[ProtocolLib.jar:?]
        ... 8 more
```

### Steps to reproduce

New install

### Plugin Version

[13:44:28 Server thread/INFO][] - Oraxen version 1.143.1
[13:44:28 Server thread/INFO][] - Author: Th0rgal

### ProtocolLib Version

[13:44:42 Server thread/INFO][] - ProtocolLib version 4.8.0
[13:44:42 Server thread/INFO][] - Provides read/write access to the Minecraft protocol.
[13:44:42 Server thread/INFO][] - Authors: dmulloy2 and comphenix

### Server Version

[13:44:55 Thread-32/INFO][] - This server is running MultiPaper version MultiPaper-1.19.2-35 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 7d8ed82)
You are running the latest version

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
Update protocollib to 5.0
if it still happens my only assumption is MultiPaper
@DoctaEnkoda
