### ISSUE TITLE
Testing on version 1.14.4 returns errors.

### ISSUE THREAD

**Issue by F4brizio** [oraxen/Oraxen#58]
When trying to run the plugin in version 1.14.4 I got the following error:

`...
[00:45:28] [Server thread/INFO]: [MythicMobs] File ExampleDropTables.yml not found! Creating a new one...
[00:45:28] [Server thread/INFO]: [MythicMobs] File ExampleRandomSpawns.yml not found! Creating a new one...
[00:45:28] [Server thread/INFO]: [MythicMobs] Spawners folder not found! Creating...
[00:45:28] [Server thread/INFO]: [MythicMobs] ? Loaded 5 mobs.
[00:45:28] [Server thread/INFO]: [MythicMobs] ? Loaded 3 vanilla mob overrides.
[00:45:28] [Server thread/INFO]: [MythicMobs] ? Loaded 0 mob stacks.
[00:45:28] [Server thread/INFO]: [MythicMobs] ? Loaded 3 skills.
[00:45:28] [Server thread/INFO]: [MythicMobs] ? Loaded 2 random spawns.
[00:45:28] [Server thread/INFO]: [MythicMobs] ? Loaded 3 mythic items.
[00:45:28] [Server thread/INFO]: [MythicMobs] ? Loaded 2 drop tables.
[00:45:28] [Server thread/INFO]: [MythicMobs] ? Loaded 0 mob spawners.
[00:45:28] [Server thread/INFO]: [MythicMobs] MythicMobs configuration file loaded successfully.
[00:45:28] [Server thread/INFO]: [MythicMobs] Started up bStats Metrics
[00:45:28] [Server thread/INFO]: [MythicMobs] ? MythicMobs v4.9.1 (build 3295) has been successfully loaded!
[00:45:28] [Server thread/INFO]: [Oraxen] Plugin "MythicMobs" detected, enabling hooks
[00:45:28] [Server thread/INFO]: [Oraxen] Plugin "CrateReloaded" detected, enabling hooks
[00:45:28] [Server thread/INFO]: [Oraxen] Plugin "BossShopPro" detected, enabling hooks
[00:45:28] [Server thread/ERROR]: Error occurred while enabling Oraxen v1.42.2 (Is it up to date?)
java.lang.NoClassDefFoundError: com/syntaxphoenix/syntaxapi/nbt/NbtTag
        at io.th0rgal.oraxen.items.ItemParser.buildItem(ItemParser.java:55) ~[?:?]
        at io.th0rgal.oraxen.settings.ConfigsManager.parsesConfig(ConfigsManager.java:137) ~[?:?]
        at io.th0rgal.oraxen.settings.ConfigsManager.parsesConfigs(ConfigsManager.java:119) ~[?:?]
        at io.th0rgal.oraxen.items.OraxenItems.loadItems(OraxenItems.java:28) ~[?:?]
        at io.th0rgal.oraxen.items.OraxenItems.loadItems(OraxenItems.java:24) ~[?:?]
        at io.th0rgal.oraxen.OraxenPlugin.onEnable(OraxenPlugin.java:73) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.ClassNotFoundException: com.syntaxphoenix.syntaxapi.nbt.NbtTag
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        ... 15 more
[00:45:28] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
>
...`
I've been trying to fix this error for a few hours, however I can't find what the problem is. Any suggestions?

I find it a very interesting project and I am only trying to understand it for educational purposes. Thank you.

**Comment by Th0rgal** [comment]
Do you have this issue with the last version?

**Comment by F4brizio** [comment]
I just did it and I still get the same error.
![image](https://user-images.githubusercontent.com/68043260/90272301-d14d9b80-de22-11ea-805d-b08bc03d4d1a.png)

Estoy usando:
- server: spigot-1.14.4
- compiler: JDK 1.8

**Comment by F4brizio** [comment]
I have a suspicion that it may be a problem when compiling. Could you share what are the characteristics with which it compiles?

**Comment by Th0rgal** [comment]
Okay got it, you need to do ``gradle buildJar``

**Comment by F4brizio** [comment]
It is true, the error was at the time of compiling, I did it using the command `gradle build` and the correct thing was `gradle buildJar`.

Thank you very much.
