### ISSUE TITLE
[BUG] Could not pass PlayerJoinEvent

### ISSUE THREAD

**Issue by BoiThiccc** [oraxen/oraxen#724]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

[14:37:01 INFO]: UUID of player XDWCFULKE is bdcb1e40-0fc2-40a2-8df8-24c9d10a16e2
[14:37:01 ERROR]: Could not pass event PlayerJoinEvent to Oraxen v${projectVersion}
java.lang.NoSuchFieldError: CUSTOM_CHAT_COMPLETIONS
        at io.th0rgal.oraxen.font.FontManager.sendGlyphTabCompletion(FontManager.java:167) ~[oraxen-1.152.2.jar:?]
        at io.th0rgal.oraxen.font.FontEvents.onPlayerJoin(FontEvents.java:217) ~[oraxen-1.152.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor946.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1632]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:363) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:305) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:320) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:576) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:231) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1651) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:37:01 INFO]: XDWCFULKE joined the game

### Steps to reproduce

Happens after somebody joins the server 

### Plugin Version

1.152.2

### Server Software & Version

Current: git-Purpur-1632 (MC: 1.18.2)*
* You are running the latest version

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
@BoiThiccc are you on ProtocolLib 5.0? if so are you on a relatively new version of it?

**Comment by BoiThiccc** [comment]
Im on 4.8 but I cannot find 5.0 on the spigot page

**Comment by Boy0000** [comment]
go in the discord and type !protlib

**Comment by Boy0000** [comment]
5.0 is a "dev version" and is not on their spigot

**Comment by BoiThiccc** [comment]
Thanks its fixed now
