### ISSUE TITLE
It worked last week but not now.

### ISSUE THREAD

**Issue by GMency** [oraxen/oraxen#741]
```[14:07:37] [Server thread/ERROR]: Error occurred while enabling Oraxen v1.152.5 (Is it up to date?)
java.lang.NoClassDefFoundError: com/massivecraft/factions/perms/PermissibleAction
	at io.th0rgal.protectionlib.ProtectionLib.lambda$init$0(ProtectionLib.java:21) ~[oraxen-1.152.5.jar:?]
	at io.th0rgal.protectionlib.ProtectionLib.handleCompatibility(ProtectionLib.java:45) ~[oraxen-1.152.5.jar:?]
	at io.th0rgal.protectionlib.ProtectionLib.init(ProtectionLib.java:21) ~[oraxen-1.152.5.jar:?]
	at io.th0rgal.oraxen.OraxenPlugin.onEnable(OraxenPlugin.java:75) ~[oraxen-1.152.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Fusion-API-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[Fusion-API-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[Fusion-API-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:611) ~[fusion-1.19.2.jar:git-Fusion-"337558e"]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:525) ~[fusion-1.19.2.jar:git-Fusion-"337558e"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[fusion-1.19.2.jar:git-Fusion-"337558e"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[fusion-1.19.2.jar:git-Fusion-"337558e"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[fusion-1.19.2.jar:git-Fusion-"337558e"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.perms.PermissibleAction
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:179) ~[Fusion-API-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[Fusion-API-1.19.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 13 more
[14:07:37] [Server thread/ERROR]: Error occurred while disabling Oraxen v1.152.5 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "io.th0rgal.oraxen.font.FontManager.unregisterEvents()" because "this.fontManager" is null
	at io.th0rgal.oraxen.OraxenPlugin.unregisterListeners(OraxenPlugin.java:138) ~[oraxen-1.152.5.jar:?]
	at io.th0rgal.oraxen.OraxenPlugin.onDisable(OraxenPlugin.java:132) ~[oraxen-1.152.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[Fusion-API-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:402) ~[Fusion-API-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:585) ~[Fusion-API-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:377) ~[Fusion-API-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:548) ~[Fusion-API-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:611) ~[fusion-1.19.2.jar:git-Fusion-"337558e"]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:525) ~[fusion-1.19.2.jar:git-Fusion-"337558e"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[fusion-1.19.2.jar:git-Fusion-"337558e"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1116) ~[fusion-1.19.2.jar:git-Fusion-"337558e"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[fusion-1.19.2.jar:git-Fusion-"337558e"]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]```

**Comment by Boy0000** [comment]
ur not providing much info here
ur using a weird fork of spigot or paper or something, and you provide an error but nothing more
@GMency if im gonna be able to do anything at all here im gonna need a full logfile put on https://mclo.gs and a screenshot of your plugins

**Comment by GMency** [comment]
https://mclo.gs/z0IenNW

![image](https://user-images.githubusercontent.com/48655904/224550956-c90d6dec-d866-4fe0-b00d-4953a1a9126f.png)

**Comment by Boy0000** [comment]
idk what plugin Factions is but im guessing thats the issue
If you have a link to its spigot page or something

**Comment by GMency** [comment]
https://www.massivecraft.com/plugins/factions

I tried to replace Towny plugin to Faction cuz of claim lag. So it's kind of chuck based region protection plugin. 🤔 As you text me I added it recently. But it's really important function for my server to protect personal area from other player.

**Comment by GMency** [comment]
this one is what I exactly use https://www.spigotmc.org/resources/saberfactions-1-8-1-19-x-discord-gg-saber-the-complete-factions-solution.69771/
