### ISSUE TITLE
[BUG] Furniture without barriers dont work

### ISSUE THREAD

**Issue by ItsEricRao** [oraxen/oraxen#767]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Furniture cannot be placed and will output the error below:
`[21:55:51 ERROR]: Could not pass event PlayerJoinEvent to Oraxen v1.154.0
java.lang.NoSuchFieldError: CUSTOM_CHAT_COMPLETIONS
        at io.th0rgal.oraxen.font.FontManager.sendGlyphTabCompletion(FontManager.java:162) ~[oraxen-1.154.0.jar:?]
        at io.th0rgal.oraxen.font.FontEvents.onPlayerJoin(FontEvents.java:205) ~[oraxen-1.154.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor683.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1626]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:363) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:305) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:320) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:576) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:201) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1648) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:522) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1482) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1626]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

### Steps to reproduce

Placing furniture without barrier can cause the problem

### Plugin Version

Oraxen version 1.154.0

### ProtocolLib Version

 ProtocolLib version 4.8.0

### Server Software & Version

Current: git-Purpur-1626 (MC: 1.18.2)*

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Defective4** [comment]
Huh

![image](https://user-images.githubusercontent.com/66302346/227738606-2b9835ba-e580-4bde-a5d9-5938c123aac5.png)
![image](https://user-images.githubusercontent.com/66302346/227738609-6b3e84c9-ccc9-4c3d-b7f5-3cdd5f8359dc.png)

**Comment by Boy0000** [comment]
@ItsEricRao 
1. the error you provided is not relevant, it is probably above
2. dont check the box saying ur using protlib 5 then say ur using protlib 4.8 when oraxen specifically says it requires protlib 5
update protlib
