### ISSUE TITLE
[BUG] Cannot read field "detectViabackwards"

### ISSUE THREAD

**Issue by untuned** [oraxen/oraxen#856]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

If you set `furniture.enabled: false` while also having ViaVersion + ViaBackwards installed, the plugin fails to load.

```
[Oraxen] Enabling Oraxen v1.156.3
Oraxen | Successfully updated settings.yml
Error occurred while enabling Oraxen v1.156.3 (Is it up to date?)
java.lang.NullPointerException: Cannot read field "detectViabackwards" because the return value of "io.th0rgal.oraxen.mechanics.provided.gameplay.furniture.FurnitureFactory.getInstance()" is null
        at io.th0rgal.oraxen.OraxenPlugin.checkIfSupportsDisplayEntities(OraxenPlugin.java:77) ~[oraxen-1.156.3.jar:?]
        at io.th0rgal.oraxen.OraxenPlugin.onEnable(OraxenPlugin.java:123) ~[oraxen-1.156.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:570) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:481) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:643) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[Oraxen] Disabling Oraxen v1.156.3
Error occurred (in the plugin loader) while disabling Oraxen v1.156.3 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "io.th0rgal.oraxen.font.FontManager.unregisterEvents()" because "this.fontManager" is null
        at io.th0rgal.oraxen.OraxenPlugin.unregisterListeners(OraxenPlugin.java:168) ~[oraxen-1.156.3.jar:?]
        at io.th0rgal.oraxen.OraxenPlugin.onDisable(OraxenPlugin.java:162) ~[oraxen-1.156.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:570) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:481) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:643) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### Steps to reproduce

1. Install Oraxen, ViaVersion, and ViaBackwards (along with dependencies)
2. Start the server without any changes to the config files.
3. Observe the console, Oraxen should load fine.
4. Stop the server
5. Set `furniture.enabled: false` in `mechanics.yml`
6. Start the server
7. Observe the console, see that Oraxen doesn't load.

### Plugin Version

```
Oraxen version 1.156.3
Authors: th0rgal and boy0000
```

### ProtocolLib Version

```
ProtocolLib version 5.0.0
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix
```

### Server Software & Version

```
Current: git-Purpur-1980 (MC: 1.19.4)*
Previous: git-Purpur-1979 (MC: 1.19.4)
* You are running the latest version
```

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
thanks will be fixed in 1.157.0 @untuned 
For now just enable furniture. Unlike most mechanics it has very little effect having it enabled or not 👍
