### ISSUE TITLE
[BUG !!!] ResourcePacks not working

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#878]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

```
Plugin Oraxen v1.157.0 generated an exception while executing task 9952
java.lang.BootstrapMethodError: bootstrap method initialization exception
        at io.th0rgal.oraxen.pack.upload.hosts.Polymath.uploadPack(Polymath.java:32) ~[oraxen-1.157.0.jar:?]
        at io.th0rgal.oraxen.pack.upload.UploadManager.lambda$uploadAsyncAndSendToPlayers$1(UploadManager.java:66) ~[oraxen-1.157.0.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

and

```
[00:17:23 ERROR]: [CommandAPI] Unhandled exception executing '/o pack send @a'
java.lang.NullPointerException: Cannot invoke "io.th0rgal.oraxen.pack.dispatch.PackSender.sendPack(org.bukkit.entity.Player)" because the return value of "io.th0rgal.oraxen.pack.upload.UploadManager.getSender()" is null
        at io.th0rgal.oraxen.commands.CommandsManager.lambda$getPackCommand$2(CommandsManager.java:104) ~[oraxen-1.157.0.jar:?]
        at dev.jorel.commandapi.executors.CommandExecutor.run(CommandExecutor.java:49) ~[?:?]
        at dev.jorel.commandapi.executors.NormalExecutor.executeWith(NormalExecutor.java:44) ~[?:?]
        at dev.jorel.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:138) ~[?:?]
        at dev.jorel.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:125) ~[?:?]
        at dev.jorel.commandapi.CommandAPIExecutor.execute(CommandAPIExecutor.java:96) ~[?:?]
        at dev.jorel.commandapi.CommandAPIHandler.lambda$generateCommand$0(CommandAPIHandler.java:256) ~[?:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.4.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:330) ~[?:?]
        at net.minecraft.commands.Commands.performPrefixedCommand(Commands.java:309) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R3.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:943) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchServerCommand(CraftServer.java:906) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:542) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:489) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:17:23 INFO]: An unexpected error occurred trying to execute that command
```

### Steps to reproduce

> try to join a server using latest oraxen version

### Plugin Version

1.157.0

### ProtocolLib Version

5.0.0

### Server Software & Version

1.19.4 Purpur 1985

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
![image](https://github.com/oraxen/oraxen/assets/62521371/b2e62369-6f0d-415a-a56c-9514b9c19d00)
works fine for me, this has always been an issue of hosts blocking urls

not to mention nothing of note has changed in this part of the code for eons
