### ISSUE TITLE
[BUG] Oraxen not loading

### ISSUE THREAD

**Issue by FitHubUser** [oraxen/oraxen#936]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Oraxen is not starting bc of this error.

[17:07:18 INFO]: [Oraxen] Enabling Oraxen v1.157.3
[17:07:18 ERROR]: Error occurred while enabling Oraxen v1.157.3 (Is it up to date?)
java.lang.NoClassDefFoundError: io/th0rgal/protectionlib/ProtectionLib
        at io.th0rgal.oraxen.OraxenPlugin.onEnable(OraxenPlugin.java:91) ~[oraxen-1.157.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-307]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-307]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-307]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.th0rgal.protectionlib.ProtectionLib
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:177) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:124) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 12 more

### Steps to reproduce

Idk

### Plugin Version

[17:09:16 INFO]: Oraxen version 1.157.3
[17:09:16 INFO]: Authors: th0rgal and boy0000

### ProtocolLib Version

[17:11:09 INFO]: ProtocolLib version 5.0.0
[17:11:09 INFO]: Provides read/write access to the Minecraft protocol.
[17:11:09 INFO]: Authors: dmulloy2 and comphenix

### Server Software & Version

[17:11:30 INFO]: This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25)

### How breaking is the bug?

Breaking Bug - Plugin unusable

**Comment by Boy0000** [comment]
did you compile it? this isnt an issue oraxen comes with normally
move this to discord

**Comment by hHyeok** [comment]
you should build by using "./gradlew build" command in console instead of Tasks - build - jar from gradle tab of intellij,
