### ISSUE TITLE
[BUG] On Furniture Place NULL

### ISSUE THREAD

**Issue by Scot-Survivor** [oraxen/oraxen#954]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I place furniture via the API, using:
```
OraxenFurniture.place(locOfFurniture, currentModelString,
                    FurnitureMechanic.yawToRotation(player.getLocation().getYaw()).rotateClockwise().rotateClockwise(),
                    BlockFace.UP);
```
However, this is producing a NPE as shown here:
```
java.lang.NullPointerException: Cannot invoke "org.bukkit.block.Block.getLocation()" because "block" is null
        at io.th0rgal.oraxen.utils.BlockHelpers.isStandingInside(BlockHelpers.java:75) ~[oraxen-1.157.2.jar:?]
        at io.th0rgal.oraxen.mechanics.provided.gameplay.furniture.FurnitureListener.getMechanic(FurnitureListener.java:206) ~[oraxen-1.157.2.jar:?]
        at io.th0rgal.oraxen.mechanics.provided.gameplay.furniture.FurnitureListener.onFurniturePlace(FurnitureListener.java:137) ~[oraxen-1.157.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor84.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[pufferfish-api-1.19.4-R0.1-SNAPSHOT.jar:git-Pufferfish-73]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfish-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:564) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:536) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1960) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1344) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1321) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1314) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1292) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[pufferfish-1.19.4.jar:git-Pufferfish-73]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        ```

### Steps to reproduce

Try to place furniture using the API, see above error.

### Plugin Version

Oraxen version 1.157.5

### ProtocolLib Version

ProtocolLib version 5.0.0

### Server Software & Version

```
[13:52:53 INFO]: Checking version, please wait...
[13:52:53 INFO]: This server is running Pufferfish version git-Pufferfish-73 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: cadfa71 on HEAD)
You are on the latest version!
Previous version: git-Paper-550 (MC: 1.19.4)
```

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
your error implies that the placement is handled via the listener and not the API
Aka ur placing it like u normally do, so idk where the API comes in here but

**Comment by Scot-Survivor** [comment]
I'm placing it, after I interact with it, I wonder if that's causing issues? (So it's listening to the on furniture interaction event)

**Comment by Boy0000** [comment]
oraxen places it on interact, so ur also calling it on interact.
aka ur double placing it. i doubt thats behaviour you want

**Comment by Scot-Survivor** [comment]
```
public boolean canCook(Player player) {
        boolean canCook = super.canCook(player);
        if (canCook && !this.currentModelString.equals(plugin.getOvenFireModelString())) {
            currentModelString = plugin.getOvenFireModelString();
        } else if (!canCook && !this.currentModelString.equals(plugin.getOvenNoFireModelString())) {
            currentModelString = plugin.getOvenNoFireModelString();
        }
        FurnitureMechanic furnitureMechanic = OraxenFurniture.getFurnitureMechanic(this.getFurnitureLocation(player).getBlock());
        if (!furnitureMechanic.getItemID().equals(currentModelString)) {
            OraxenFurniture.remove(this.getFurnitureLocation(player), player);
            Location locOfFurniture = this.getFurnitureLocation(player);
            OraxenFurniture.place(locOfFurniture, currentModelString,
                    FurnitureMechanic.yawToRotation(((int)player.getLocation().getYaw())+180).rotateClockwise().rotateCounterClockwise(),
                    BlockFace.UP);
        }
        return canCook;
    }
```

This is the exact method

**Comment by Scot-Survivor** [comment]
Oh sorry, this is actually called under an inventoryclick event, not a furniture interact event

**Comment by Boy0000** [comment]
i have no clue when ur calling this still

**Comment by Scot-Survivor** [comment]
Furniture Interact Event -> Open inventory

upon a click event inside this opened inventory "canCook" is called, to check canCook, this is then overridden as shown, to place the other furniture model in the same spot. 

it behaves as expected, and works without issue (from what I can see), the error itself doesn't break anything, obviously fills up the server logs. 

When attaching a debugger, I couldn't find exactly when the player or block became null, which confused me even more

**Comment by Boy0000** [comment]
unable to reproduce this, must be some issue in your code
I can replace furniture just fine it seems so

the error doesnt really make sense either so
